"""
Extended Kali tools - the rest of the tools we haven't covered yet.
Mobile, cloud, AD, C2, API fuzzing, code analysis, containers, social eng, IoT, Bluetooth, fuzzing, and more.
"""

from nova_arsenal.kali_blueprint import ToolInfo

# ═══════════════════════════════════════════════════════════════════════════
# MOBILE SECURITY
# ═══════════════════════════════════════════════════════════════════════════

MOBILE_TOOLS = [
    ToolInfo(
        name="drozer",
        category="mobile",
        description="Android security testing framework",
        install_path="/usr/bin/drozer",
        binary="drozer",
        usage="drozer [options]",
        examples=[
            "drozer console connect",
            "drozer console connect --server 192.168.1.100",
        ],
        flags={"console connect": "Connect to device", "--server": "Remote server"},
        notes="Requires agent APK installed on target. Use 'adb forward tcp:31415 tcp:31415' first.",
    ),
    ToolInfo(
        name="frida",
        category="mobile",
        description="Dynamic instrumentation toolkit (Android/iOS/Windows/Linux/macOS)",
        install_path="/usr/bin/frida",
        binary="frida",
        usage="frida [options]",
        examples=[
            "frida-ps -U",
            "frida-ps -Uai",
            "frida -U -f com.target.app -l hook.js --no-pause",
            "frida-trace -U -i open com.target.app",
            "frida-discover -U",
        ],
        flags={
            "-U": "USB device",
            "-D": "Device by ID",
            "-f": "Spawn process",
            "-l": "Load script",
            "--no-pause": "Auto-resume",
            "-p": "Attach by PID",
            "-n": "Attach by name",
            "-i": "Include (trace function)",
            "-x": "Exclude",
        },
        notes="Most powerful instrumentation tool. Scripts written in JavaScript.",
    ),
    ToolInfo(
        name="objection",
        category="mobile",
        description="Runtime mobile exploration toolkit (powered by Frida)",
        install_path="/usr/bin/objection",
        binary="objection",
        usage="objection [options]",
        examples=[
            "objection -g com.target.app explore",
            "objection -g com.target.app explore --startup-command 'android root disable'",
            "objection -g com.target.app explore -c 'android sslpinning disable'",
        ],
        flags={
            "-g": "Gadget/package",
            "explore": "Start REPL",
            "-c": "Startup command",
            "--startup-command": "Run on connect",
        },
        notes="Pre-built Frida scripts for common tasks: SSL pinning bypass, root detection, etc.",
    ),
    ToolInfo(
        name="apkleaks",
        category="mobile",
        description="Scan APK files for URIs, endpoints, and secrets",
        install_path="/usr/bin/apkleaks",
        binary="apkleaks",
        usage="apkleaks [options] -f <apk>",
        examples=[
            "apkleaks -f app.apk",
            "apkleaks -f app.apk -s",
        ],
        flags={"-f": "APK file", "-s": "Scan only", "-p": "Pattern file", "-o": "Output file"},
    ),
    ToolInfo(
        name="apkx",
        category="mobile",
        description="Extract and analyze APK packages",
        install_path="/usr/bin/apkx",
        binary="apkx",
        usage="apkx [options] <apk>",
        examples=["apkx app.apk", "apkx -d app.apk"],
        flags={"-d": "Decompile", "-b": "Build"},
    ),
    ToolInfo(
        name="jadx",
        category="mobile",
        description="Android DEX/APK to Java source decompiler",
        install_path="/usr/bin/jadx",
        binary="jadx",
        usage="jadx [options] <file>",
        examples=["jadx app.apk", "jadx -d output/ app.apk --show-bad-code"],
        flags={"-d": "Output dir", "--show-bad-code": "Show problematic code", "-j": "Threads"},
    ),
    ToolInfo(
        name="jadx-gui",
        category="mobile",
        description="GUI version of jadx",
        install_path="/usr/bin/jadx-gui",
        binary="jadx-gui",
        usage="jadx-gui [file]",
        examples=["jadx-gui app.apk"],
        flags={},
    ),
    ToolInfo(
        name="apktool",
        category="mobile",
        description="APK reverse engineering (decode/rebuild)",
        install_path="/usr/bin/apktool",
        binary="apktool",
        usage="apktool [command] <file>",
        examples=["apktool d app.apk", "apktool b app/", "apktool if framework-res.apk"],
        flags={"d": "Decode", "b": "Build", "if": "Install framework"},
    ),
    ToolInfo(
        name="dex2jar",
        category="mobile",
        description="Convert DEX files to JAR",
        install_path="/usr/bin/d2j-dex2jar",
        binary="d2j-dex2jar",
        usage="d2j-dex2jar [options] <file>",
        examples=["d2j-dex2jar app.apk -o app.jar"],
        flags={"-o": "Output file"},
    ),
    ToolInfo(
        name="qark",
        category="mobile",
        description="Quick Android Review Kit (static analysis)",
        install_path="/usr/bin/qark",
        binary="qark",
        usage="qark [options]",
        examples=["qark --apk app.apk", "qark --sourcepath /path/to/source"],
        flags={"--apk": "APK file", "--sourcepath": "Source directory", "--exploit": "Build exploit"},
    ),
    ToolInfo(
        name="mobisf",
        category="mobile",
        description="Mobile Security Framework (automated Android/iOS analysis)",
        install_path="/usr/bin/mobisf",
        binary="mobisf",
        usage="mobisf [options]",
        examples=["mobisf"],
        flags={},
        notes="Web-based. Start server then upload APK/IPA for analysis.",
    ),
    ToolInfo(
        name="apkid",
        category="mobile",
        description="Android application identifier (packers, obfuscators, SDKs)",
        install_path="/usr/bin/apkid",
        binary="apkid",
        usage="apkid [options] <file>",
        examples=["apkid app.apk", "apkid -j app.apk"],
        flags={"-j": "JSON output", "-o": "Output file", "-t": "Tool output"},
    ),
    ToolInfo(
        name="radare2",
        category="mobile",
        description="Reverse engineering framework (also for Android binaries)",
        install_path="/usr/bin/r2",
        binary="r2",
        usage="r2 [options] <file>",
        examples=["r2 -A libnative.so"],
        flags={"-A": "Analyze", "-q": "Quiet"},
        notes="Can analyze native Android libraries (.so files).",
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# CLOUD SECURITY
# ═══════════════════════════════════════════════════════════════════════════

CLOUD_TOOLS = [
    ToolInfo(
        name="cloud_enum",
        category="cloud",
        description="Multi-cloud OSINT tool (AWS, Azure, GCP)",
        install_path="/usr/bin/cloud_enum",
        binary="cloud_enum",
        usage="cloud_enum [options] -k <keyword>",
        examples=[
            "cloud_enum -k mycompany",
            "cloud_enum -k mycompany -t 50",
        ],
        flags={"-k": "Keyword", "-t": "Threads", "-l": "Log file"},
        notes="Checks S3 buckets, Azure blobs, GCP buckets, and more.",
    ),
    ToolInfo(
        name="pacu",
        category="cloud",
        description="AWS exploitation framework",
        install_path="/usr/bin/pacu",
        binary="pacu",
        usage="pacu [options]",
        examples=["pacu", "pacu --module-name s3_bucket__list_all_buckets --region us-east-1"],
        flags={"--module-name": "Module to run", "--region": "AWS region"},
        notes="Modular framework. Modules: iam__enum_users_roles_policies_groups, s3_bucket__list_all_buckets, etc.",
    ),
    ToolInfo(
        name="scoutsuite",
        category="cloud",
        description="Multi-cloud security auditing tool",
        install_path="/usr/bin/scout",
        binary="scout",
        usage="scout [provider] [options]",
        examples=[
            "scout aws --access-key ACCESS --secret-key SECRET",
            "scout azure --tenant TENANT",
            "scout gcp --user-account",
        ],
        flags={"--access-key": "AWS access key", "--secret-key": "AWS secret key", "--tenant": "Azure tenant"},
        notes="Generates HTML report with security findings.",
    ),
    ToolInfo(
        name="cloudsploit",
        category="cloud",
        description="Cloud security posture management",
        install_path="/usr/bin/cloudsploit",
        binary="cloudsploit",
        usage="cloudsploit [options]",
        examples=["cloudsploit", "cloudsploit --config config.js"],
        flags={"--config": "Config file"},
        notes="Checks for misconfigurations across AWS, Azure, GCP.",
    ),
    ToolInfo(
        name="s3scanner",
        category="cloud",
        description="Scan for open S3 buckets",
        install_path="/usr/bin/s3scanner",
        binary="s3scanner",
        usage="s3scanner [options]",
        examples=["s3scanner scan -f buckets.txt", "s3scanner scan -b bucket-name"],
        flags={"-f": "File with bucket names", "-b": "Bucket name", "scan": "Scan mode"},
    ),
    ToolInfo(
        name="bucket-finder",
        category="cloud",
        description="Scan for open S3 buckets and list contents",
        install_path="/usr/bin/bucket-finder",
        binary="bucket-finder",
        usage="bucket-finder [options]",
        examples=["bucket-finder --buckets-file buckets.txt"],
        flags={"--buckets-file": "Bucket names file"},
    ),
    ToolInfo(
        name="microburin",
        category="cloud",
        description="AWS penetration testing toolkit",
        install_path="/usr/bin/microburin",
        binary="microburin",
        usage="microburin [options]",
        examples=["microburin", "microburin --enum"],
        flags={"--enum": "Enumerate"},
    ),
    ToolInfo(
        name="enumerate-iam",
        category="cloud",
        description="Enumerate AWS IAM permissions from access keys",
        install_path="/usr/bin/enumerate-iam",
        binary="enumerate-iam",
        usage="enumerate-iam --access-key ACCESS --secret-key SECRET",
        examples=["enumerate-iam --access-key AKIA... --secret-key ..."],
        flags={"--access-key": "AWS access key", "--secret-key": "AWS secret key"},
    ),
    ToolInfo(
        name="endpoints",
        category="cloud",
        description="AWS/GCP/Azure endpoint enumeration",
        install_path="/usr/bin/endpoints",
        binary="endpoints",
        usage="endpoints [options]",
        examples=["endpoints --service ec2"],
        flags={"--service": "Cloud service"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# ACTIVE DIRECTORY
# ═══════════════════════════════════════════════════════════════════════════

AD_TOOLS = [
    ToolInfo(
        name="bloodhound",
        category="active_directory",
        description="Active Directory attack path analysis (graph-based)",
        install_path="/usr/bin/bloodhound",
        binary="bloodhound-python",
        usage="bloodhound-python [options]",
        examples=[
            "bloodhound-python -u user -p pass -d domain.com -c All",
            "bloodhound-python -u user -p pass -d domain.com -c DCOnly",
            "bloodhound-python -u user --hashes aad3b... -d domain.com -c All -ns 192.168.1.1",
        ],
        flags={
            "-u": "Username", "-p": "Password", "-d": "Domain",
            "-c": "Collection method (All, DCOnly, Session, LoggedOn, etc.)",
            "-ns": "Nameserver", "--hashes": "NTLM hash", "-k": "Kerberos",
            "-o": "Output directory",
        },
        notes="Collects data -> import into BloodHound GUI -> find attack paths.",
    ),
    ToolInfo(
        name="impacket",
        category="active_directory",
        description="Network protocols toolkit (Windows/AD attacks)",
        install_path="/usr/bin/impacket-secretsdump",
        binary="impacket-secretsdump",
        usage="impacket-<tool> [options]",
        examples=[
            "impacket-secretsdump domain/user:password@192.168.1.1",
            "impacket-secretsdump domain/user -hashes aad3b...:hash@192.168.1.1",
            "impacket-smbclient domain/user:password@192.168.1.1",
            "impacket-psexec domain/user:password@192.168.1.1",
            "impacket-wmiexec domain/user:password@192.168.1.1",
            "impacket-smbexec domain/user:password@192.168.1.1",
            "impacket-getTGT domain/user:password",
            "impacket-GetUserSPNs domain/user:password -request",
            "impacket-ticketer -nthash hash -domain-sid S-1-5... -domain domain.com user",
            "impacket-ticketConverter ticket.kirbi ticket.ccache",
        ],
        flags={},
        notes="Essential AD toolkit. Key tools: secretsdump, psexec, wmiexec, smbexec, getTGT, GetUserSPNs, ticketer, ticketConverter, mssqlclient, ntlmrelayx.",
    ),
    ToolInfo(
        name="rubeus",
        category="active_directory",
        description="Kerberos abuse toolkit (Windows)",
        install_path="/usr/bin/rubeus",
        binary="Rubeus.exe",
        usage="Rubeus.exe [command] [options]",
        examples=[
            "Rubeus.exe kerberoast /outfile:hashes.txt",
            "Rubeus.exe asreproast /outfile:asrep.txt",
            "Rubeus.exe s4u /user:svc_sql /rc4:hash /impersonateuser:administrator /msdsspn:cifs/target.domain.com",
            "Rubeus.exe ptt /ticket:ticket.kirbi",
            "Rubeus.exe harvest /interval:30",
        ],
        flags={
            "kerberoast": "Kerberoast SPN accounts",
            "asreproast": "AS-REP roast accounts",
            "s4u": "S4U2Self/S4U2Proxy",
            "ptt": "Pass-the-ticket",
            "harvest": "Harvest TGTs",
            "asktgt": "Request TGT",
            "triangle": "Rubeus triangle",
        },
        notes="Windows tool. Use via Cobalt Strike or upload to target.",
    ),
    ToolInfo(
        name="kerbrute",
        category="active_directory",
        description="Kerberos pre-auth brute force tool",
        install_path="/usr/bin/kerbrute",
        binary="kerbrute",
        usage="kerbrute [command] [options]",
        examples=[
            "kerbrute userenum --dc dc.domain.com -d domain.com users.txt",
            "kerbrute passwordspray --dc dc.domain.com -d domain.com users.txt password",
            "kerbrute bruteforce --dc dc.domain.com -d domain.com combos.txt",
        ],
        flags={
            "--dc": "Domain controller", "-d": "Domain",
            "userenum": "Username enumeration", "passwordspray": "Password spray",
            "bruteforce": "Brute force",
        },
        notes="Uses Kerberos pre-authentication which is stealthier than LDAP brute force.",
    ),
    ToolInfo(
        name="adidnsdump",
        category="active_directory",
        description="AD DNS dumping tool",
        install_path="/usr/bin/adidnsdump",
        binary="adidnsdump",
        usage="adidnsdump [options] <target>",
        examples=[
            "adidnsdump domain.com -u user -p password",
            "adidnsdump domain.com -u user -p password -r",
        ],
        flags={"-u": "Username", "-p": "Password", "-r": "Resolve records"},
    ),
    ToolInfo(
        name="ldapdomaindump",
        category="active_directory",
        description="LDAP domain information dumper",
        install_path="/usr/bin/ldapdomaindump",
        binary="ldapdomaindump",
        usage="ldapdomaindump [options] <target>",
        examples=[
            "ldapdomaindump -u user -p pass domain.com",
            "ldapdomaindump -u user -p pass -o output/ domain.com",
        ],
        flags={"-u": "Username", "-p": "Password", "-o": "Output directory"},
    ),
    ToolInfo(
        name="ldeep",
        category="active_directory",
        description="LDAP enumeration tool",
        install_path="/usr/bin/ldeep",
        binary="ldeep",
        usage="ldeep [options] <command>",
        examples=[
            "ldeep ldap -u user -p pass -d domain.com all output/",
            "ldeep ldap -u user -p pass -d domain.com users",
        ],
        flags={"-u": "Username", "-p": "Password", "-d": "Domain", "-s": "LDAP server"},
    ),
    ToolInfo(
        name="bloodyAD",
        category="active_directory",
        description="AD privilege escalation tool",
        install_path="/usr/bin/bloodyAD",
        binary="bloodyAD",
        usage="bloodyAD [options] <command>",
        examples=[
            "bloodyAD -d domain.com -u user -p pass --host 192.168.1.1 add user pwned 'Password123'",
            "bloodyAD -d domain.com -u user -p pass --host 192.168.1.1 add groupMember Domain Admins user",
        ],
        flags={"-d": "Domain", "-u": "Username", "-p": "Password", "--host": "DC host"},
    ),
    ToolInfo(
        name="certipy",
        category="active_directory",
        description="AD Certificate Services (ADCS) abuse tool",
        install_path="/usr/bin/certipy",
        binary="certipy",
        usage="certipy [options] <command>",
        examples=[
            "certipy find -u user@domain.com -p password -dc-ip 192.168.1.1",
            "certipy req -u user@domain.com -p password -ca CA-NAME -template Template",
            "certipy forge -ca-pfx ca.pfx -upn administrator@domain.com",
        ],
        flags={"-u": "Username", "-p": "Password", "-dc-ip": "DC IP", "-ca": "CA name", "-template": "Certificate template"},
    ),
    ToolInfo(
        name="coercer",
        category="active_directory",
        description="NTLM coercion tool (PetitPotam, PrinterBug, etc.)",
        install_path="/usr/bin/coercer",
        binary="coercer",
        usage="coercer [options]",
        examples=[
            "coercer scan -t 192.168.1.1 -u user -p pass",
            "coercer coerce -t 192.168.1.1 -u user -p pass --method PetitPotam",
        ],
        flags={"-t": "Target", "-u": "Username", "-p": "Password", "--method": "Coercion method"},
    ),
    ToolInfo(
        name="ntlmrelayx",
        category="active_directory",
        description="NTLM relay attack tool (from Impacket)",
        install_path="/usr/bin/impacket-ntlmrelayx",
        binary="impacket-ntlmrelayx",
        usage="impacket-ntlmrelayx [options]",
        examples=[
            "impacket-ntlmrelayx -t 192.168.1.1 -smb2support",
            "impacket-ntlmrelayx -t ldap://192.168.1.1 --escalate-user user",
            "impacket-ntlmrelayx -t mssql://192.168.1.1 -q 'SELECT @@version'",
        ],
        flags={"-t": "Target", "-smb2support": "SMB2 support", "-e": "Execute", "-q": "Query"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# C2 FRAMEWORKS
# ═══════════════════════════════════════════════════════════════════════════

C2_TOOLS = [
    ToolInfo(
        name="sliver",
        category="c2",
        description="Open-source cross-platform C2 framework",
        install_path="/usr/bin/sliver",
        binary="sliver",
        usage="sliver [options]",
        examples=[
            "sliver-server",
            "sliver-client",
        ],
        flags={"server": "Start server", "client": "Connect to server"},
        notes="Modern C2 with MTLS, HTTP(S), DNS, WireGuard implants. Supports Go, C++, C#, Python.",
    ),
    ToolInfo(
        name="covenant",
        category="c2",
        description="Collaborative C2 framework (.NET)",
        install_path="/usr/bin/covenant",
        binary="covenant",
        usage="covenant [options]",
        examples=["covenant", "covenant --rest"],
        flags={"--rest": "REST API"},
        notes="ASP.NET Core. Web UI at https://localhost:7443.",
    ),
    ToolInfo(
        name="havoc",
        category="c2",
        description="Modern C2 framework (Havoc Framework)",
        install_path="/usr/bin/havoc",
        binary="havoc",
        usage="havoc [options]",
        examples=["havoc server --profile ./profiles/havoc.yaotl"],
        flags={"--profile": "C2 profile"},
        notes="Requires teamserver. Profile-based configuration.",
    ),
    ToolInfo(
        name="brute_ratel",
        category="c2",
        description="Red team C2 framework (evasion-focused)",
        install_path="/usr/bin/brute_ratel",
        binary="bruteratel",
        usage="bruteratel [options]",
        examples=["bruteratel"],
        flags={},
        notes="Commercial. Advanced evasion techniques.",
    ),
    ToolInfo(
        name="mythic",
        category="c2",
        description="Collaborative, multi-platform C2 framework",
        install_path="/usr/bin/mythic",
        binary="mythic",
        usage="mythic [options]",
        examples=["sudo ./mythic-cli start"],
        flags={"start": "Start Mythic", "stop": "Stop Mythic"},
        notes="Docker-based. Supports multiple agent types.",
    ),
    ToolInfo(
        name="poshc2",
        category="c2",
        description="Proxy aware C2 framework with PowerShell and Python implant support",
        install_path="/usr/bin/poshc2",
        binary="poshc2-server",
        usage="poshc2-server [options]",
        examples=["poshc2-server"],
        flags={},
    ),
    ToolInfo(
        name="smbexec",
        category="c2",
        description="SMB-based command execution",
        install_path="/usr/bin/impacket-smbexec",
        binary="impacket-smbexec",
        usage="impacket-smbexec [options]",
        examples=["impacket-smbexec domain/user:password@192.168.1.1"],
        flags={},
        notes="Part of Impacket suite.",
    ),
    ToolInfo(
        name="ligolo-ng",
        category="c2",
        description="Tunneling/pivoting tool (like Chisel but better)",
        install_path="/usr/bin/ligolo-ng",
        binary="ligolo-ng",
        usage="ligolo-ng [options]",
        examples=[
            "ligolo-proxy -selfcert -laddr 0.0.0.0:11601",
            "ligolo-agent -connect PROXY_IP:11601 -retry -ignore-cert",
        ],
        flags={"-selfcert": "Self-signed cert", "-laddr": "Listen address", "-connect": "Connect to proxy"},
        notes="Creates TUN interface for transparent pivoting.",
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# API / WEB FUZZING
# ═══════════════════════════════════════════════════════════════════════════

API_FUZZING_TOOLS = [
    ToolInfo(
        name="arjun",
        category="api_fuzzing",
        description="HTTP parameter discovery suite",
        install_path="/usr/bin/arjun",
        binary="arjun",
        usage="arjun [options]",
        examples=[
            "arjun -u https://example.com/page",
            "arjun -u https://example.com/page -m GET,POST",
            "arjun -i urls.txt -o output.json",
            "arjun -u https://example.com/page -w /usr/share/seclists/Discovery/Web-Content/burp-parameter-names.txt",
        ],
        flags={
            "-u": "URL", "-m": "Methods (GET,POST,JSON,XML)", "-i": "Input file",
            "-o": "Output file", "-w": "Wordlist", "-t": "Threads",
            "--json": "JSON output", "-c": "Cookie",
        },
        notes="Discovers hidden parameters. Essential for API testing.",
    ),
    ToolInfo(
        name="kiterunner",
        category="api_fuzzing",
        description="API endpoint discovery and fuzzing tool",
        install_path="/usr/bin/kiterunner",
        binary="kr",
        usage="kr [command] [options]",
        examples=[
            "kr scan https://example.com -w routes-large.kite",
            "kr brute https://example.com/api -w routes-large.kite",
            "kr scan https://example.com -H 'Authorization: Bearer token' -w routes-large.kite",
        ],
        flags={
            "-w": "Wordlist", "-H": "Header", "-x": "Extensions",
            "--method": "HTTP method", "-d": "Depth",
        },
        notes="Specialized for API routes. Use routes-large.kite for comprehensive scanning.",
    ),
    ToolInfo(
        name="hakrawler",
        category="api_fuzzing",
        description="Web crawler for discovery of endpoints and assets",
        install_path="/usr/bin/hakrawler",
        binary="hakrawler",
        usage="hakrawler [options]",
        examples=[
            "echo https://example.com | hakrawler",
            "hakrawler -d 3 -u https://example.com",
            "echo https://example.com | hakrawler -json",
        ],
        flags={"-d": "Depth", "-u": "URL", "-json": "JSON output", "-insecure": "Skip TLS verify"},
    ),
    ToolInfo(
        name="gospider",
        category="api_fuzzing",
        description="Fast web spider written in Go",
        install_path="/usr/bin/gospider",
        binary="gospider",
        usage="gospider [options]",
        examples=[
            "gospider -s https://example.com -d 3",
            "gospider -s https://example.com -c 10 -d 5 --sitemap",
        ],
        flags={
            "-s": "Site", "-d": "Depth", "-c": "Concurrency",
            "--sitemap": "Parse sitemap", "-j": "Parse JS",
            "-o": "Output directory",
        },
    ),
    ToolInfo(
        name="paramspider",
        category="api_fuzzing",
        description="Parameter miner for web apps",
        install_path="/usr/bin/paramspider",
        binary="paramspider",
        usage="paramspider [options]",
        examples=["paramspider -d example.com", "paramspider -d example.com -s"],
        flags={"-d": "Domain", "-s": "Silent", "-l": "Level"},
    ),
    ToolInfo(
        name="x8",
        category="api_fuzzing",
        description="Hidden API discovery tool (alternative to Kiterunner)",
        install_path="/usr/bin/x8",
        binary="x8",
        usage="x8 [options]",
        examples=["x8 -u https://example.com -wordlist api.txt"],
        flags={"-u": "URL", "-wordlist": "Wordlist", "-threads": "Threads", "-o": "Output"},
    ),
    ToolInfo(
        name="swagger-hack",
        category="api_fuzzing",
        description="Swagger/OpenAPI endpoint enumeration and testing",
        install_path="/usr/bin/swagger-hack",
        binary="swagger-hack",
        usage="swagger-hack [options]",
        examples=["swagger-hack --mode all https://example.com/swagger.json"],
        flags={"--mode": "Mode (all, test)", "-o": "Output"},
    ),
    ToolInfo(
        name="ffuf",
        category="api_fuzzing",
        description="Fast web fuzzer (also for API parameter fuzzing)",
        install_path="/usr/bin/ffuf",
        binary="ffuf",
        usage="ffuf -u https://example.com/api/FUZZ -w api-params.txt -mc 200",
        examples=[
            "ffuf -u https://example.com/api/v1/users -H 'Authorization: Bearer TOKEN' -w ids.txt -mc 200 -mr 'id'",
        ],
        flags={},
        notes="See web tools section for full flags. FUZZ in URL, headers, or POST data.",
    ),
    ToolInfo(
        name="wpscan",
        category="api_fuzzing",
        description="WordPress REST API enumeration",
        install_path="/usr/bin/wpscan",
        binary="wpscan",
        usage="wpscan --url <url> --enumerate vp,vt,u --api-token TOKEN",
        examples=[
            "wpscan --url https://example.com --enumerate vp,vt,u --api-token TOKEN",
        ],
        flags={},
        notes="REST API: /wp-json/wp/v2/users for user enumeration.",
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# CODE ANALYSIS / SAST
# ═══════════════════════════════════════════════════════════════════════════

CODE_ANALYSIS_TOOLS = [
    ToolInfo(
        name="semgrep",
        category="code_analysis",
        description="Static analysis tool for finding bugs (fast, multi-language)",
        install_path="/usr/bin/semgrep",
        binary="semgrep",
        usage="semgrep [options] <pattern|config>",
        examples=[
            "semgrep --config auto .",
            "semgrep --config p/security-audit .",
            "semgrep --config 'r/python.lang.security' .",
            "semgrep --config p/owasp-top-ten .",
            "semgrep scan --config auto --json",
        ],
        flags={
            "--config": "Config (auto, p/security-audit, p/owasp-top-ten, etc.)",
            "--json": "JSON output", "-o": "Output file",
            "--severity": "Filter severity", "--exclude": "Exclude paths",
            "scan": "Scan mode",
        },
        notes="1000+ community rules. Supports Python, Java, JS, Go, Ruby, etc.",
    ),
    ToolInfo(
        name="bandit",
        category="code_analysis",
        description="Python security linter (finds common security issues)",
        install_path="/usr/bin/bandit",
        binary="bandit",
        usage="bandit [options] <file|directory>",
        examples=[
            "bandit -r .",
            "bandit -r . -f json -o results.json",
            "bandit -r . -ll",
        ],
        flags={
            "-r": "Recursive", "-f": "Format (json, csv, txt, html)",
            "-o": "Output file", "-ll": "High severity only",
            "-iii": "Medium severity only",
        },
    ),
    ToolInfo(
        name="grype",
        category="code_analysis",
        description="Vulnerability scanner for container images and filesystems",
        install_path="/usr/bin/grype",
        binary="grype",
        usage="grype [options] <target>",
        examples=[
            "grype dir:.",
            "grype docker:myapp:latest",
            "grype registry:myapp:latest --fail-on high",
        ],
        flags={
            "dir:": "Directory", "docker:": "Docker image",
            "registry:": "Registry image", "--fail-on": "Fail on severity",
            "-o": "Output format (json, table)",
        },
    ),
    ToolInfo(
        name="trivy",
        category="code_analysis",
        description="Comprehensive security scanner (containers, filesystems, git, IaC)",
        install_path="/usr/bin/trivy",
        binary="trivy",
        usage="trivy [command] [options] <target>",
        examples=[
            "trivy image myapp:latest",
            "trivy fs .",
            "trivy repo https://github.com/user/repo",
            "trivy config ./terraform/",
            "trivy fs --severity HIGH,CRITICAL .",
        ],
        flags={
            "image": "Scan container image", "fs": "Scan filesystem",
            "repo": "Scan git repo", "config": "Scan IaC (Terraform, CloudFormation, K8s)",
            "--severity": "Filter severity", "--format": "Output format",
            "--exit-code": "Exit code on vulnerability",
        },
        notes="Most comprehensive vulnerability scanner. Supports containers, code, IaC, SBOM.",
    ),
    ToolInfo(
        name="checkov",
        category="code_analysis",
        description="Static analysis for infrastructure as code (IaC)",
        install_path="/usr/bin/checkov",
        binary="checkov",
        usage="checkov [options] <directory>",
        examples=[
            "checkov -d .",
            "checkov -d . --framework terraform",
            "checkov -d . --check CKV_AWS_18",
            "checkov -d . -o json",
        ],
        flags={
            "-d": "Directory", "--framework": "Framework (terraform, cloudformation, kubernetes)",
            "--check": "Specific check ID", "-o": "Output format",
            "--skip-check": "Skip check",
        },
    ),
    ToolInfo(
        name="tfsec",
        category="code_analysis",
        description="Terraform security scanner",
        install_path="/usr/bin/tfsec",
        binary="tfsec",
        usage="tfsec [options] <directory>",
        examples=["tfsec .", "tfsec . --format json", "tfsec . --exclude-downloaded-modules"],
        flags={"--format": "Output format", "--exclude-downloaded-modules": "Exclude modules"},
    ),
    ToolInfo(
        name="kics",
        category="code_analysis",
        description="Keeping Infrastructure as Code Secure (Checkmarx)",
        install_path="/usr/bin/kics",
        binary="kics",
        usage="kics [command] [options]",
        examples=[
            "kics scan -p .",
            "kics scan -p . --report-formats json",
        ],
        flags={"scan": "Scan mode", "-p": "Path", "--report-formats": "Output formats"},
    ),
    ToolInfo(
        name="gosec",
        category="code_analysis",
        description="Go security checker",
        install_path="/usr/bin/gosec",
        binary="gosec",
        usage="gosec [options] <package>",
        examples=["gosec ./...", "gosec -json ./..."],
        flags={"-json": "JSON output", "-fmt": "Format", "-exclude": "Exclude rules"},
    ),
    ToolInfo(
        name="njsscan",
        category="code_analysis",
        description="Node.js security scanner (SAST)",
        install_path="/usr/bin/njsscan",
        binary="njsscan",
        usage="njsscan [options] <path>",
        examples=["njsscan .", "njsscan --json ."],
        flags={"--json": "JSON output", "-o": "Output file"},
    ),
    ToolInfo(
        name="phpcs",
        category="code_analysis",
        description="PHP CodeSniffer (PSR standards and security)",
        install_path="/usr/bin/phpcs",
        binary="phpcs",
        usage="phpcs [options] <file>",
        examples=["phpcs --standard=PSR2 .", "phpcs --standard=Security *.php"],
        flags={"--standard": "Standard (PSR2, PSR12, Security)", "-n": "No warnings", "--report": "Report format"},
    ),
    ToolInfo(
        name="spotbugs",
        category="code_analysis",
        description="Java bug finder (static analysis)",
        install_path="/usr/bin/spotbugs",
        binary="spotbugs",
        usage="spotbugs [options] <jar|class>",
        examples=["spotbugs -textui -effort:max target/", "spotbugs -html -output report.html target/"],
        flags={"-effort": "Effort (min, max)", "-html": "HTML output", "-textui": "Text output"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# CONTAINER SECURITY
# ═══════════════════════════════════════════════════════════════════════════

CONTAINER_TOOLS = [
    ToolInfo(
        name="trivy",
        category="container",
        description="Comprehensive vulnerability scanner for containers",
        install_path="/usr/bin/trivy",
        binary="trivy",
        usage="trivy image <image>",
        examples=[
            "trivy image nginx:latest",
            "trivy image --severity HIGH,CRITICAL myapp:latest",
        ],
        flags={"--severity": "Filter severity", "--format": "Output format"},
        notes="See code analysis section for full usage.",
    ),
    ToolInfo(
        name="grype",
        category="container",
        description="Vulnerability scanner for container images",
        install_path="/usr/bin/grype",
        binary="grype",
        usage="grype <image>",
        examples=["grype nginx:latest", "grype docker:myapp:latest"],
        flags={},
        notes="See code analysis section for full usage.",
    ),
    ToolInfo(
        name="docker-bench",
        category="container",
        description="Docker CIS benchmark checker",
        install_path="/usr/bin/docker-bench-security",
        binary="docker-bench-security",
        usage="docker-bench-security [options]",
        examples=["docker-bench-security", "docker-bench-security -c 2.1"],
        flags={"-c": "Check ID", "-l": "Log file"},
        notes="Runs as Docker container: docker run --net host --pid host --userns host ...",
    ),
    ToolInfo(
        name="dockle",
        category="container",
        description="Container image linter (best practices)",
        install_path="/usr/bin/dockle",
        binary="dockle",
        usage="dockle [options] <image>",
        examples=["dockle myapp:latest", "dockle --exit-code 1 myapp:latest"],
        flags={"--exit-code": "Exit code on findings", "--exit-level": "Exit level"},
    ),
    ToolInfo(
        name="notary",
        category="container",
        description="Docker content trust (image signing)",
        install_path="/usr/bin/notary",
        binary="notary",
        usage="notary [command] [options]",
        examples=["notary list docker.io/library/nginx"],
        flags={"list": "List signatures"},
    ),
    ToolInfo(
        name="clair",
        category="container",
        description="Container vulnerability analyzer (static analysis)",
        install_path="/usr/bin/clair",
        binary="clair",
        usage="clair [options]",
        examples=["clair -config config.yaml"],
        flags={"-config": "Config file"},
        notes="Usually deployed as a service. Scans OCI images.",
    ),
    ToolInfo(
        name="docker-scanner",
        category="container",
        description="Docker security scanner",
        install_path="/usr/bin/docker-scanner",
        binary="docker-scanner",
        usage="docker-scanner [options] <image>",
        examples=["docker-scanner scan myapp:latest"],
        flags={"scan": "Scan mode"},
    ),
    ToolInfo(
        name="sysdig",
        category="container",
        description="Container runtime security and forensics",
        install_path="/usr/bin/sysdig",
        binary="sysdig",
        usage="sysdig [options]",
        examples=[
            "sysdig",
            "sysdig -pc container.name=nginx",
            "sysdig -w capture.scap",
        ],
        flags={"-pc": "Container mode", "-w": "Write to file", "-r": "Read from file"},
    ),
    ToolInfo(
        name="falco",
        category="container",
        description="Cloud-native runtime security (Kubernetes threat detection)",
        install_path="/usr/bin/falco",
        binary="falco",
        usage="falco [options]",
        examples=["falco", "falco -r rules.yaml"],
        flags={"-r": "Rules file", "-o": "Output"},
    ),
    ToolInfo(
        name="kube-hunter",
        category="container",
        description="Kubernetes penetration testing tool",
        install_path="/usr/bin/kube-hunter",
        binary="kube-hunter",
        usage="kube-hunter [options]",
        examples=[
            "kube-hunter",
            "kube-hunter --remote 192.168.1.100",
            "kube-hunter --active",
        ],
        flags={"--remote": "Remote target", "--active": "Active scanning", "--pod": "Run as pod"},
    ),
    ToolInfo(
        name="kubeaudit",
        category="container",
        description="Kubernetes security auditing",
        install_path="/usr/bin/kubeaudit",
        binary="kubeaudit",
        usage="kubeaudit [command]",
        examples=[
            "kubeaudit all",
            "kubeaudit privileged",
            "kubeaudit rootfs",
        ],
        flags={"all": "All checks", "privileged": "Privileged container check", "rootfs": "Root filesystem check"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# SOCIAL ENGINEERING
# ═══════════════════════════════════════════════════════════════════════════

SOCIAL_ENGINEERING_TOOLS = [
    ToolInfo(
        name="set",
        category="social_engineering",
        description="Social Engineering Toolkit (SET)",
        install_path="/usr/bin/setoolkit",
        binary="setoolkit",
        usage="setoolkit",
        examples=["setoolkit"],
        flags={},
        notes="GUI/text-based. Attack vectors: Spear-Phishing, Website Attack Vectors, Infectious Media Generator.",
    ),
    ToolInfo(
        name="gophish",
        category="social_engineering",
        description="Phishing framework",
        install_path="/usr/bin/gophish",
        binary="gophish",
        usage="gophish [options]",
        examples=["gophish"],
        flags={"-config": "Config file"},
        notes="Web-based UI. Start with: ./gophish",
    ),
    ToolInfo(
        name="Evilginx2",
        category="social_engineering",
        description="Man-in-the-middle attack framework (phishing with session hijacking)",
        install_path="/usr/bin/evilginx2",
        binary="evilginx2",
        usage="evilginx2 [options]",
        examples=["evilginx2", "evilginx2 -p /path/phishlets"],
        flags={"-p": "Phishlets directory"},
        notes="Bypasses 2FA by proxying real login. Phishlets for Google, O365, etc.",
    ),
    ToolInfo(
        name="socal",
        category="social_engineering",
        description="Social media OSINT framework",
        install_path="/usr/bin/socal",
        binary="socal",
        usage="socal [options]",
        examples=["socal"],
        flags={},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# FUZZING
# ═══════════════════════════════════════════════════════════════════════════

FUZZING_TOOLS = [
    ToolInfo(
        name="afl++",
        category="fuzzing",
        description="American Fuzzy Lop++ (coverage-guided fuzzer)",
        install_path="/usr/bin/afl-fuzz",
        binary="afl-fuzz",
        usage="afl-fuzz [options] -- <target> [params]",
        examples=[
            "afl-fuzz -i input/ -o output/ -- target @@",
            "afl-fuzz -i input/ -o output/ -m none -- target @@",
            "afl-cc -o target target.c",
            "afl-showmap -i input/ -- target @@",
        ],
        flags={
            "-i": "Input directory", "-o": "Output directory",
            "-m": "Memory limit", "-t": "Timeout",
            "--": "Separator before target",
        },
        notes="Requires instrumented binary (use afl-cc/afl-gcc). Most popular fuzzer.",
    ),
    ToolInfo(
        name="honggfuzz",
        category="fuzzing",
        description="Multi-threaded feedback-driven fuzzer",
        install_path="/usr/bin/honggfuzz",
        binary="honggfuzz",
        usage="honggfuzz [options] -- <target>",
        examples=[
            "honggfuzz -i input/ -- target @@",
            "honggfuzz -n 4 -t 5 -- target @@",
        ],
        flags={"-i": "Input dir", "-n": "Threads", "-t": "Timeout", "-r": "Regex"},
        notes="Supports hardware feedback (Intel PT, Intel BTS).",
    ),
    ToolInfo(
        name="libfuzzer",
        category="fuzzing",
        description="In-process, coverage-guided fuzzer (LLVM)",
        install_path="/usr/bin/clang",
        binary="clang",
        usage="clang -fsanitize=fuzzer -o target target.c",
        examples=[
            "clang -fsanitize=fuzzer,address -o target target.c",
            "./target corpus/",
        ],
        flags={"-fsanitize=fuzzer": "Enable libFuzzer", "-fsanitize=address": "Enable ASan"},
        notes="Built into LLVM/Clang. Use with ASan for memory bug detection.",
    ),
    ToolInfo(
        name="radamsa",
        category="fuzzing",
        description="General-purpose test case generator (mutation-based)",
        install_path="/usr/bin/radamsa",
        binary="radamsa",
        usage="radamsa [options] <sample>",
        examples=[
            "echo 'AAAA' | radamsa",
            "radamsa -n 1000 input.txt > corpus/",
            "cat request.txt | radamsa | curl -d @- http://target/api",
        ],
        flags={"-n": "Number of samples", "-o": "Output file", "-s": "Seed"},
        notes="Great for generating malformed inputs for network protocols.",
    ),
    ToolInfo(
        name="boofuzz",
        category="fuzzing",
        description="Network protocol fuzzer (Sulley successor)",
        install_path="/usr/bin/boofuzz",
        binary="boofuzz",
        usage="boofuzz [options]",
        examples=["boofuzz", "boofuzz --target 192.168.1.1:21"],
        flags={"--target": "Target host:port", "-l": "Listen", "-p": "Port"},
        notes="Python-based. Define protocols in Python scripts.",
    ),
    ToolInfo(
        name="dharma",
        category="fuzzing",
        description="Grammar-based file fuzzer",
        install_path="/usr/bin/dharma",
        binary="dharma",
        usage="dharma [options]",
        examples=["dharma -g grammar.json -o output/"],
        flags={"-g": "Grammar file", "-o": "Output directory"},
    ),
    ToolInfo(
        name="zzuf",
        category="fuzzing",
        description="Transparent application input fuzzer",
        install_path="/usr/bin/zzuf",
        binary="zzuf",
        usage="zzuf [options] -- <program>",
        examples=[
            "zzuf -s 0:1000 -- cat file",
            "zzuf -s 0:100 -T 5 -- ./target",
        ],
        flags={"-s": "Seed range", "-T": "Threads", "-f": "Fuzz ratio", "-r": "Byte range"},
    ),
    ToolInfo(
        name="american-fuzzy-lop",
        category="fuzzing",
        description="Original AFL fuzzer (superseded by AFL++)",
        install_path="/usr/bin/afl-fuzz",
        binary="afl-fuzz",
        usage="afl-fuzz [options] -- <target>",
        examples=[],
        flags={},
        notes="Use AFL++ instead.",
    ),
    ToolInfo(
        name="qsym",
        category="fuzzing",
        description="QEMU-based hybrid fuzzer (concolic execution)",
        install_path="/usr/bin/qsym",
        binary="qsym",
        usage="qsym [options] -- <target>",
        examples=["qsym -i input/ -o output/ -- target @@"],
        flags={"-i": "Input dir", "-o": "Output dir"},
    ),
    ToolInfo(
        name="peach",
        category="fuzzing",
        description="Peach Fuzzer (model-based)",
        install_path="/usr/bin/peach",
        binary="peach",
        usage="peach [options] <pit>",
        examples=["peach pit.xml"],
        flags={"pit": "PIT file (protocol/model definition)"},
        notes="Model-based fuzzer. Define protocol models in XML.",
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# IoT / SCADA / ICS
# ═══════════════════════════════════════════════════════════════════════════

IOT_SCADA_TOOLS = [
    ToolInfo(
        name="mbtget",
        category="iot_scada",
        description="Modbus TCP client tool",
        install_path="/usr/bin/mbtget",
        binary="mbtget",
        usage="mbtget [options] <target>",
        examples=[
            "mbtget -u 1 -r 10 192.168.1.100",
            "mbtget -u 1 -w 0x0001 192.168.1.100",
        ],
        flags={"-u": "Unit ID", "-r": "Read holding registers", "-w": "Write single register"},
    ),
    ToolInfo(
        name="metasploit",
        category="iot_scada",
        description="SCADA/ICS modules in Metasploit",
        install_path="/usr/bin/msfconsole",
        binary="msfconsole",
        usage="msfconsole -q -x 'search type:auxiliary scada'",
        examples=[
            "msfconsole -q -x 'use auxiliary/scada/modbus_findunitid; set RHOSTS 192.168.1.100; run'",
        ],
        flags={},
        notes="Search: search type:auxiliary scada. Modules for Modbus, DNP3, BACnet, OPC, EtherNet/IP.",
    ),
    ToolInfo(
        name="firmwalker",
        category="iot_scada",
        description="Firmware analysis script (searches for passwords, keys, URLs)",
        install_path="/usr/bin/firmwalker",
        binary="firmwalker.sh",
        usage="./firmwalker.sh <firmware_dir>",
        examples=["./firmwalker.sh /tmp/extracted/"],
        flags={},
        notes="Searches for: passwords, certificates, private keys, URLs, IP addresses.",
    ),
    ToolInfo(
        name="binwalk",
        category="iot_scada",
        description="Firmware extraction (essential for IoT analysis)",
        install_path="/usr/bin/binwalk",
        binary="binwalk",
        usage="binwalk -e firmware.bin",
        examples=["binwalk -e firmware.bin", "binwalk -Me firmware.bin"],
        flags={"-e": "Extract", "-M": "Recursive"},
        notes="See forensics section for full flags.",
    ),
    ToolInfo(
        name="unsquashfs",
        category="iot_scada",
        description="SquashFS filesystem extractor (common in firmware)",
        install_path="/usr/bin/unsquashfs",
        binary="unsquashfs",
        usage="unsquashfs [options] <image>",
        examples=["unsquashfs squashfs-root.img", "unsquashfs -d output/ squashfs-root.img"],
        flags={"-d": "Destination dir"},
    ),
    ToolInfo(
        name="sasquatch",
        category="iot_scada",
        description="SquashFS extractor with non-standard options (for firmware)",
        install_path="/usr/bin/sasquatch",
        binary="sasquatch",
        usage="sasquatch [options] <image>",
        examples=["sasquatch firmware.squashfs"],
        flags={},
        notes="Handles non-standard SquashFS variants used in firmware.",
    ),
    ToolInfo(
        name="ubireader_extract_images",
        category="iot_scada",
        description="UBI image extractor (common in embedded Linux)",
        install_path="/usr/bin/ubireader_extract_images",
        binary="ubireader_extract_images",
        usage="ubireader_extract_images [options] <image>",
        examples=["ubireader_extract_images ubi.img"],
        flags={"-o": "Output dir"},
    ),
    ToolInfo(
        name="ubireader_extract_files",
        category="iot_scada",
        description="UBI filesystem extractor",
        install_path="/usr/bin/ubireader_extract_files",
        binary="ubireader_extract_files",
        usage="ubireader_extract_files [options] <image>",
        examples=["ubireader_extract_files ubi.img"],
        flags={"-o": "Output dir"},
    ),
    ToolInfo(
        name="firmware-mod-kit",
        category="iot_scada",
        description="Firmware modification toolkit",
        install_path="/usr/bin/firmware-mod-kit",
        binary="fmk",
        usage="fmk [command] [options]",
        examples=[
            "extract-firmware.sh firmware.bin",
            "build-firmware.sh output/",
        ],
        flags={},
        notes="Scripts: extract-firmware.sh, build-firmware.sh, unpack-firmware.sh, repack-firmware.sh.",
    ),
    ToolInfo(
        name="routerkeygen",
        category="iot_scada",
        description="Router WEP/WPA key generator (for known vulnerabilities)",
        install_path="/usr/bin/routerkeygen",
        binary="routerkeygen",
        usage="routerkeygen [options] <capture>",
        examples=["routerkeygen -i capture.cap"],
        flags={"-i": "Input capture"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# BLUETOOTH
# ═══════════════════════════════════════════════════════════════════════════

BLUETOOTH_TOOLS = [
    ToolInfo(
        name="btscanner",
        category="bluetooth",
        description="Bluetooth scanner and enumeration tool",
        install_path="/usr/bin/btscanner",
        binary="btscanner",
        usage="btscanner",
        examples=["btscanner"],
        flags={},
        notes="Interactive ncurses interface.",
    ),
    ToolInfo(
        name="spooftooph",
        category="bluetooth",
        description="Bluetooth spoofing and scanning tool",
        install_path="/usr/bin/spooftooph",
        binary="spooftooph",
        usage="spooftooph [options]",
        examples=[
            "spooftooph -i hci0 -a",
            "spooftooph -i hci0 -s 00:11:22:33:44:55 -n 'Friendly Name'",
        ],
        flags={"-i": "Interface", "-a": "Auto-scan", "-s": "Spoof address", "-n": "Name"},
    ),
    ToolInfo(
        name="bluelog",
        category="bluetooth",
        description="Bluetooth logger (passive scanning)",
        install_path="/usr/bin/bluelog",
        binary="bluelog",
        usage="bluelog [options]",
        examples=["bluelog -i hci0", "bluelog -i hci0 -o log.txt"],
        flags={"-i": "Interface", "-o": "Output file", "-t": "Timeout"},
    ),
    ToolInfo(
        name="redfang",
        category="bluetooth",
        description="Bluetooth discovery tool (find non-visible devices)",
        install_path="/usr/bin/redfang",
        binary="redfang",
        usage="redfang [options]",
        examples=["redfang -i hci0"],
        flags={"-i": "Interface"},
    ),
    ToolInfo(
        name="Ubertooth",
        category="bluetooth",
        description="Bluetooth sniffing tool (requires Ubertooth hardware)",
        install_path="/usr/bin/ubertooth-btbb",
        binary="ubertooth-btbb",
        usage="ubertooth-btbb [options]",
        examples=["ubertooth-btbb"],
        flags={},
        notes="Requires Ubertooth One hardware. For Bluetooth LE sniffing: ubertooth-btle.",
    ),
    ToolInfo(
        name="bettercap",
        category="bluetooth",
        description="BLE (Bluetooth Low Energy) attack tool",
        install_path="/usr/bin/bettercap",
        binary="bettercap",
        usage="bettercap -eval 'ble.recon on'",
        examples=["bettercap -eval 'set ble.interface hci0; ble.recon on'"],
        flags={"ble.recon": "BLE reconnaissance"},
        notes="Also covers network attacks. See network section.",
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# REVERSE ENGINEERING (Additional)
# ═══════════════════════════════════════════════════════════════════════════

REVERSE_ENGINEERING_EXTRA = [
    ToolInfo(
        name="angr",
        category="reverse_engineering",
        description="Binary analysis framework (symbolic execution)",
        install_path="/usr/bin/angr",
        binary="python3",
        usage="import angr",
        examples=[
            "python3 -c 'import angr; p = angr.Project(\"binary\"); print(p.loader)'",
        ],
        flags={},
        notes="Python library. Use for symbolic execution, constraint solving, decompilation.",
    ),
    ToolInfo(
        name="ROPgadget",
        category="reverse_engineering",
        description="ROP gadget finder",
        install_path="/usr/bin/ROPgadget",
        binary="ROPgadget",
        usage="ROPgadget [options] <binary>",
        examples=["ROPgadget --binary binary", "ROPgadget --binary binary --ropchain"],
        flags={"--binary": "Binary", "--ropchain": "Generate ROP chain", "--only": "Filter gadgets"},
    ),
    ToolInfo(
        name="one_gadget",
        category="reverse_engineering",
        description="Find one-shot RCE gadgets in libc",
        install_path="/usr/bin/one_gadget",
        binary="one_gadget",
        usage="one_gadget <libc>",
        examples=["one_gadget /lib/x86_64-linux-gnu/libc.so.6"],
        flags={},
        notes="Finds magic gadgets that give RCE in one shot.",
    ),
    ToolInfo(
        name="retdec",
        category="reverse_engineering",
        description="Retargetable decompiler",
        install_path="/usr/bin/retdec-decompiler",
        binary="retdec-decompiler",
        usage="retdec-decompiler [options] <binary>",
        examples=["retdec-decompiler binary"],
        flags={"-o": "Output dir", "--backend": "Backend (llvm, troll, x86)"},
        notes="Supports x86, x86-64, ARM, MIPS, PowerPC.",
    ),
    ToolInfo(
        name="binaryninja",
        category="reverse_engineering",
        description="Binary analysis platform (commercial)",
        install_path="/usr/bin/binaryninja",
        binary="binaryninja",
        usage="binaryninja [file]",
        examples=["binaryninja binary"],
        flags={},
        notes="Commercial. Demo version available.",
    ),
    ToolInfo(
        name=" Cutter",
        category="reverse_engineering",
        description="Free reverse engineering platform (GUI for radare2/Rizin)",
        install_path="/usr/bin/cutter",
        binary="cutter",
        usage="cutter [file]",
        examples=["cutter binary"],
        flags={},
        notes="GUI alternative to radare2. Built on Rizin.",
    ),
    ToolInfo(
        name="rizin",
        category="reverse_engineering",
        description="Reverse engineering framework (radare2 fork)",
        install_path="/usr/bin/rizin",
        binary="rizin",
        usage="rizin [options] <file>",
        examples=["rizin -A binary", "rizin -qc 'aaa;afl' binary"],
        flags={"-A": "Analyze", "-q": "Quiet", "-c": "Command"},
        notes="Radare2 fork with cleaner API.",
    ),
    ToolInfo(
        name="capa",
        category="reverse_engineering",
        description="Capability detection for PE/ELF/Mach-O binaries",
        install_path="/usr/bin/capa",
        binary="capa",
        usage="capa [options] <file>",
        examples=["capa binary", "capa -j binary"],
        flags={"-j": "JSON output", "-r": "Rules path", "-t": "Tag filter"},
        notes="Identifies capabilities like 'persistence', 'privilege escalation', 'C2'.",
    ),
    ToolInfo(
        name="detect-it-easy",
        category="reverse_engineering",
        description="Binary identification tool (PEiD alternative)",
        install_path="/usr/bin/die",
        binary="die",
        usage="die [options] <file>",
        examples=["die binary"],
        flags={},
        notes="Identifies: compiler, packer, crypto, EXE type.",
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# LOG ANALYSIS / FORENSICS (Additional)
# ═══════════════════════════════════════════════════════════════════════════

LOG_FORENSICS_TOOLS = [
    ToolInfo(
        name="logparser",
        category="log_forensics",
        description="Windows Event Log analysis tool",
        install_path="/usr/bin/logparser",
        binary="logparser",
        usage="logparser [options]",
        examples=["logparser -i evtx -o csv *.evtx"],
        flags={"-i": "Input format", "-o": "Output format"},
    ),
    ToolInfo(
        name="eventlog explorer",
        category="log_forensics",
        description="Windows Event Log viewer",
        install_path="/usr/bin/evtx_dump",
        binary="evtx_dump",
        usage="evtx_dump [options] <file>",
        examples=["evtx_dump -o json system.evtx"],
        flags={"-o": "Output format (json, xml)"},
    ),
    ToolInfo(
        name="plaso",
        category="log_forensics",
        description="Super timeline forensics tool (log2timeline)",
        install_path="/usr/bin/log2timeline.py",
        binary="log2timeline.py",
        usage="log2timeline.py [options] <output> <input>",
        examples=["log2timeline.py timeline.plaso disk.img"],
        flags={"-o": "Output", "--storage-file": "Storage file"},
    ),
    ToolInfo(
        name="timesketch",
        category="log_forensics",
        description="Collaborative forensic timeline analysis",
        install_path="/usr/bin/timesketch",
        binary="timesketch",
        usage="timesketch [command]",
        examples=["timesketch import timeline.csv"],
        flags={"import": "Import timeline"},
        notes="Web-based. Deploy with Docker.",
    ),
    ToolInfo(
        name="hayabusa",
        category="log_forensics",
        description="Windows event log fast forensics timeline generator",
        install_path="/usr/bin/hayabusa",
        binary="hayabusa",
        usage="hayabusa [command] [options]",
        examples=[
            "hayabusa csv-timeline -d logs/ -o timeline.csv",
            "hayabusa logon-summary -d logs/",
        ],
        flags={"csv-timeline": "CSV timeline", "logon-summary": "Logon summary", "-d": "Directory", "-o": "Output"},
    ),
    ToolInfo(
        name="chainsaw",
        category="log_forensics",
        description="Windows forensic artifact searcher (fast, SIGMA-based)",
        install_path="/usr/bin/chainsaw",
        binary="chainsaw",
        usage="chainsaw [command] [options]",
        examples=[
            "chainsaw search -s 'EventId=4624' evtx/",
            "chainsaw attack -s sigma/ evtx/",
        ],
        flags={"search": "Search events", "attack": "Apply SIGMA rules", "-s": "Search string", "-s sigma": "SIGMA rules dir"},
    ),
    ToolInfo(
        name="mparser",
        category="log_forensics",
        description="MFT parser for NTFS forensics",
        install_path="/usr/bin/mparser",
        binary="mparser",
        usage="mparser [options] <mft>",
        examples=["mparser -m mft -o output/"],
        flags={"-m": "MFT file", "-o": "Output directory"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# ANONYMITY / PRIVACY
# ═══════════════════════════════════════════════════════════════════════════

ANONYMITY_TOOLS = [
    ToolInfo(
        name="tor",
        category="anonymity",
        description="The Onion Router (anonymous networking)",
        install_path="/usr/bin/tor",
        binary="tor",
        usage="tor [options]",
        examples=["tor", "tor --SocksPort 9050"],
        flags={"--SocksPort": "SOCKS proxy port", "--DataDirectory": "Data dir"},
        notes="Configure proxy: SOCKS5 127.0.0.1:9050",
    ),
    ToolInfo(
        name="proxychains",
        category="anonymity",
        description="Route traffic through proxy chains (SOCKS/HTTP)",
        install_path="/usr/bin/proxychains",
        binary="proxychains",
        usage="proxychains [options] <command>",
        examples=[
            "proxychains nmap -sV target.com",
            "proxychains curl http://target.com",
            "proxychains ssh user@target.com",
        ],
        flags={"-f": "Config file", "-q": "Quiet"},
        notes="Config at /etc/proxychains4.conf. Supports SOCKS4/5, HTTP, chain.",
    ),
    ToolInfo(
        name="proxychains4",
        category="anonymity",
        description="Enhanced proxychains (newer version)",
        install_path="/usr/bin/proxychains4",
        binary="proxychains4",
        usage="proxychains4 [options] <command>",
        examples=["proxychains4 curl http://ifconfig.me"],
        flags={"-f": "Config file", "-q": "Quiet"},
    ),
    ToolInfo(
        name="torsocks",
        category="anonymity",
        description="Route traffic through Tor",
        install_path="/usr/bin/torsocks",
        binary="torsocks",
        usage="torsocks [options] <command>",
        examples=[
            "torsocks curl http://ifconfig.me",
            "torsocks nmap -sV target.com",
        ],
        flags={"--port": "Tor SOCKS port"},
    ),
    ToolInfo(
        name="nyx",
        category="anonymity",
        description="Tor relay operator tool (CLI dashboard)",
        install_path="/usr/bin/nyx",
        binary="nyx",
        usage="nyx [options]",
        examples=["nyx"],
        flags={"-p": "Control port"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# EXPLOIT DEVELOPMENT (Additional)
# ═══════════════════════════════════════════════════════════════════════════

EXPLOIT_DEV_TOOLS = [
    ToolInfo(
        name="pwntools",
        category="exploit_dev",
        description="CTF framework and exploit development library",
        install_path="/usr/lib/python3/dist-packages/pwnlib/",
        binary="pwn",
        usage="from pwn import *",
        examples=[
            "pwn template ./binary > exploit.py",
            "python3 -c 'from pwn import *; p=remote(\"target\",4444)'",
        ],
        flags={},
        notes="Python library. See exploitation section.",
    ),
    ToolInfo(
        name="ROPgadget",
        category="exploit_dev",
        description="ROP gadget finder and chain builder",
        install_path="/usr/bin/ROPgadget",
        binary="ROPgadget",
        usage="ROPgadget --binary <binary>",
        examples=["ROPgadget --binary binary --ropchain"],
        flags={"--binary": "Binary", "--ropchain": "Generate ROP chain"},
    ),
    ToolInfo(
        name="one_gadget",
        category="exploit_dev",
        description="Find one-shot RCE gadgets in libc",
        install_path="/usr/bin/one_gadget",
        binary="one_gadget",
        usage="one_gadget <libc>",
        examples=["one_gadget /lib/x86_64-linux-gnu/libc.so.6"],
        flags={},
    ),
    ToolInfo(
        name="ropper",
        category="exploit_dev",
        description="ROP gadget finder (alternative to ROPgadget)",
        install_path="/usr/bin/ropper",
        binary="ropper",
        usage="ropper -f <binary>",
        examples=["ropper -f binary --search 'pop rdi'"],
        flags={"-f": "File", "--search": "Search gadgets"},
    ),
    ToolInfo(
        name="checksec",
        category="exploit_dev",
        description="Binary security checker",
        install_path="/usr/bin/checksec",
        binary="checksec",
        usage="checksec --file=<binary>",
        examples=["checksec --file=binary"],
        flags={"--file": "Binary file"},
    ),
    ToolInfo(
        name="shellcraft",
        category="exploit_dev",
        description="Shellcode generator (from pwntools)",
        install_path="/usr/bin/shellcraft",
        binary="shellcraft",
        usage="shellcraft [arch] [os] [shellcode]",
        examples=[
            "shellcraft -f asm x64.sh",
            "shellcraft -f asm x86.sh",
            "shellcraft -f elf x64.sh -o shell.elf",
        ],
        flags={"-f": "Format (asm, elf, raw)", "-o": "Output file"},
    ),
    ToolInfo(
        name="asm",
        category="exploit_dev",
        description="Assembler/disassembler (from pwntools)",
        install_path="/usr/bin/pwn",
        binary="pwn",
        usage="pwn asm / pwn disasm",
        examples=[
            "pwn asm 'mov eax, 1; int 0x80' -f raw",
            "pwn disasm 90909090",
        ],
        flags={},
    ),
    ToolInfo(
        name="cyclic",
        category="exploit_dev",
        description="Pattern generator for buffer overflow (from pwntools)",
        install_path="/usr/bin/cyclic",
        binary="cyclic",
        usage="cyclic [options]",
        examples=[
            "cyclic 200",
            "cyclic -l 0x6161616a",
        ],
        flags={"-l": "Find offset", "-a": "Alphabet", "-n": "Length"},
    ),
    ToolInfo(
        name="exploit-db",
        category="exploit_dev",
        description="Local exploit-DB search (searchsploit)",
        install_path="/usr/bin/searchsploit",
        binary="searchsploit",
        usage="searchsploit [options] <term>",
        examples=["searchsploit apache 2.4.49", "searchsploit --cve 2021-44228"],
        flags={},
        notes="See exploitation section for full flags.",
    ),
    ToolInfo(
        name="ghidra",
        category="exploit_dev",
        description="Software reverse engineering framework (NSA)",
        install_path="/opt/ghidra/",
        binary="ghidra",
        usage="ghidra / analyzeHeadless",
        examples=["analyzeHeadless /tmp/project Project -import binary"],
        flags={},
        notes="See reverse engineering section.",
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# AI & LLM SECURITY
# ═══════════════════════════════════════════════════════════════════════════

AI_SECURITY_TOOLS = [
    ToolInfo(
        name="garak",
        category="ai_security",
        description="LLM vulnerability scanner (hallucination, injection, etc.)",
        install_path="/usr/bin/garak",
        binary="garak",
        usage="garak [options]",
        examples=["garak --model_type openai --model_name gpt-3.5-turbo"],
        flags={"--model_type": "Model provider", "--model_name": "Model ID"},
        notes="The 'nmap' of LLM security.",
    ),
    ToolInfo(
        name="inspect",
        category="ai_security",
        description="Framework for evaluating LLM safety and capabilities",
        install_path="/usr/bin/inspect",
        binary="inspect",
        usage="inspect eval [options]",
        examples=["inspect eval safety.py"],
        flags={},
    ),
    ToolInfo(
        name="pyrit",
        category="ai_security",
        description="Python Risk Identification Tool for LLMs (Microsoft)",
        install_path="/usr/bin/pyrit",
        binary="pyrit",
        usage="pyrit [options]",
        examples=["pyrit --target azure_openai"],
        flags={},
    ),
    ToolInfo(
        name="llm-fuzzer",
        category="ai_security",
        description="Fuzzing tool for LLM endpoints",
        install_path="/usr/bin/llm-fuzzer",
        binary="llm-fuzzer",
        usage="llm-fuzzer --url <url>",
        examples=["llm-fuzzer --url http://localhost:8000/v1/chat/completions"],
        flags={},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# HARDWARE & SDR
# ═══════════════════════════════════════════════════════════════════════════

HARDWARE_TOOLS = [
    ToolInfo(
        name="rtl_433",
        category="hardware",
        description="Decode radio signals from ISM band (433MHz, etc.)",
        install_path="/usr/bin/rtl_433",
        binary="rtl_433",
        usage="rtl_433 [options]",
        examples=["rtl_433 -f 433.92M"],
        flags={"-f": "Frequency", "-F": "Output format"},
    ),
    ToolInfo(
        name="hackrf_transfer",
        category="hardware",
        description="HackRF transmit and receive tool",
        install_path="/usr/bin/hackrf_transfer",
        binary="hackrf_transfer",
        usage="hackrf_transfer [options]",
        examples=["hackrf_transfer -r sample.bin -f 433920000"],
        flags={"-r": "Receive to file", "-t": "Transmit from file", "-f": "Frequency in Hz"},
    ),
    ToolInfo(
        name="flashrom",
        category="hardware",
        description="Identify, read, write, verify and erase flash chips",
        install_path="/usr/bin/flashrom",
        binary="flashrom",
        usage="flashrom [options]",
        examples=["flashrom -p ch341a_spi -r bios.bin"],
        flags={"-p": "Programmer type", "-r": "Read", "-w": "Write"},
    ),
    ToolInfo(
        name="openocd",
        category="hardware",
        description="Open On-Chip Debugger (JTAG/SWD)",
        install_path="/usr/bin/openocd",
        binary="openocd",
        usage="openocd -f <config>",
        examples=["openocd -f interface/stlink.cfg -f target/stm32f4x.cfg"],
        flags={"-f": "Configuration file"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# VEHICLE HACKING
# ═══════════════════════════════════════════════════════════════════════════

VEHICLE_TOOLS = [
    ToolInfo(
        name="cansniffer",
        category="vehicle",
        description="Display CAN traffic differences",
        install_path="/usr/bin/cansniffer",
        binary="cansniffer",
        usage="cansniffer [options] <can-interface>",
        examples=["cansniffer -c can0"],
        flags={"-c": "Color output"},
    ),
    ToolInfo(
        name="cansend",
        category="vehicle",
        description="Send a single CAN frame",
        install_path="/usr/bin/cansend",
        binary="cansend",
        usage="cansend <can-interface> <can-frame>",
        examples=["cansend can0 123#DEADBEEF"],
        flags={},
    ),
    ToolInfo(
        name="candump",
        category="vehicle",
        description="Dump CAN traffic",
        install_path="/usr/bin/candump",
        binary="candump",
        usage="candump [options] <can-interface>",
        examples=["candump -L can0"],
        flags={"-L": "Log in ASCII format"},
    ),
]
